### ISSUE TITLE
View Model classes and life cycle methods

### ISSUE THREAD

**Issue by chandmk** [aurelia/framework#107]
If my view model contains activate method defined, it appears that this gets invoked in two scenarios

a. when this view model is invoked as part of navigation
b. when this view model is used in compose method

This activate method is not being called when this view model is used as view component/custom element.  

````
// app.html
<template>
<require from="./comment-list"></require>
<comment-list></comment-list>
</template>
```
```
//comment-list.js
export class CommentList {
  activate() {
   console.log('activate called');
  }
}
````
At the surface all view models look identical.  But how you use them make them behave differently.

**Comment by EisenbergEffect** [comment]
There are two lifecycles: the component/view lifecycle and the navigation lifecycle. Everything goes through the component lifecycle. The navigation lifecycle is something that the router implements and enforces. We can't unify these two as it would create a tremendous overhead and performance issues, making the entire framework unusable.

The compose element implements one extra hook "activate" in order to allow passing data into a dynamically composed view model.
