### ISSUE TITLE
@dynamicOptions not working?

### ISSUE THREAD

**Issue by grofit** [aurelia/framework#143]
I have made a plunker demonstrating the issue:
http://plnkr.co/edit/5TuZfq

After talking to @jdanyow about how this decorator should function it was mentioned that the dynamic options would be applied directly to the class instance however in this case the attributes on the custom element are not applied to the class.

There is no documentation I could find on intended behavior so I am not sure if this is a bug or it is not the expected use case, but I could do with knowing how I can access `arg-1` and `arg2` in the above example.

**Comment by jdanyow** [comment]
We need to add more documentation around `@dynamicOptions`.

Here's the example I gave in the gitter:

```html
<template>
  <pre foo="a: 1000; b: 'a string literal'; c.bind: message"></pre>
</template>
```
```javascript
import {dynamicOptions, customAttribute, inject} from 'aurelia-framework';

export class App {
  message = "Hello World!";
}

@customAttribute('foo')
@dynamicOptions()
@inject(Element)
export class Foo {
  constructor(element) {
    this.element = element;
  }

  bind() {
    var element = this.element;
    this.element = null; // so we can stringify.
    element.textContent = JSON.stringify(this, null, 2);
  }
}
```

Which displays:
```html
{
  "element": null,
  "a": "1000",
  "b": "'a string literal'",
  "c": "Hello World!"
}
```

**Comment by EisenbergEffect** [comment]
You cannot have dynamic options on the custom element. It only applies to custom attributes.

**Comment by grofit** [comment]
I am sure we will continue this conversation in gitter, but the use case here is not an attribute but a custom element, and not all arguments will be known at design time, so I need some way to support custom attributes on the element and then pass those through to a class which will know what its looking for.

**Comment by EisenbergEffect** [comment]
If you want you can create a separate custom attribute that is intended to be used on your custom element. You can then have the custom attribute's class injected into the constructor of your custom element so that they can collaborate. You would have to embed all dynamic properties inside of that one attribute though. That's the only way to do it currently. There are no dynamic options available as part of custom element currently.

**Comment by grofit** [comment]
:( well thats fair enough, and like you say this thread is specifically about it being a bug, but its just not being used correctly here so I am happy to close this.

Is there anything on the roadmap for allowing this use case? feel free to pm me on gitter if you want more info on why I am trying to do this.

**Comment by EisenbergEffect** [comment]
There's a possibility of enabling it. Bear in mind that dynamic options don't perform as well because we have to do extra work every time the element is used, as apposed to just one time to set up the prototype. How many options are you talking about. Can you give me a few more details? We do have a new capability coming to elements that lets you have a single `propertyChanged` callback across all element properties. Maybe that would help out?

**Comment by grofit** [comment]
in this instance propertyChanged would not be of much benefit as the code for this would be run once and then left.

To give some more context I was just messing around trying to port some knockout libs I wrote over to aurelia as they share a lot of overlap. So for example the one I started on was:

https://github.com/grofit/knockout.generate

So the idea is rather than providing a model and a template (as you may do with compose) you can just generate the DOM elements procedurally saving having to write and maintain a template for simple things (and also saving http and extra processing calls). Anyway so regardless of how useful it is that is the scenario I started with as it has quite a few touch points with more complicated things, like dynamic runtime binding to DOM elements, custom attributes/elements and other bits.

So the general process would be you have a custom element (attribute in the KO world) and you pass that a model (mandatory argument) then you can pass some options for generation. This will then as a 1 time thing upon attach (or init in the KO world) create DOM elements based upon the schema of your model and then dump them in with bindings, and then setup the binding context behind the scenes to use the model mentioned. This way if the data changes that's fine and the DOM elements created will update as expected but the custom element has no need to do anything.

So with the above scenario in mind the actual creation of the DOM elements is handled by another class which is just an implementation of a generic `TemplateGenerator` so the idea is anyone can make their own template generators like `BootstrapTemplateGenerator` or `MyConventionsBasedTemplateGenerator` and they will be passed the model to generate from and whatever options are provided (the dynamic attributes in this case).

So there is a `DefaultTemplateGenerator` which will want to know about idPrefix/Suffix if labels and placeholders are needed and a couple of other things. However if I were to then use this on one of my other projects I may also want to add some more custom processing to a custom template generator meaning I would need new/different args, so the gist of it all is that only the generator will know what options it expects, and ideally there may be multiple generators available (in the KO world there was a type and a visitor pattern style approach occured to find the right generator for the right type) so its not like you would be able to define at design time all the attributes the element should have.

Now there are some work arounds, like I could have a mandatory attribute called `options` which is just populated as a custom attribute like you mention above, but it will not be as nice and readable (hence going with an element for handling this rather than a custom attribute).

So anyway that will give you the overall scenario and approach taken, some bits are missing from the aurelia one, but the current work in progress is:

https://github.com/grofit/aurelia-generate

**Comment by EisenbergEffect** [comment]
In this specific case, I would inject the element into your constructor and inspect it's attributes to build up your configuration object. Just map all attributes to simple key/value pairs on an object, skipping the `using-model` attribute, which you want to be a bindable.

I would also move all your code out of attached and into `bind` so that the view is generated before it's attached to the DOM, enabling more efficient rendering.

On a related note, I'm considering a new feature to the template engine which would allow it to convert HTML into plain JS objects which would be set as a property on a custom element. So, for elements that have a lot of configuration that they want done in HTML, their custom element can receive that information as a strongly typed object, pre-parsed from the HTML markup. These objects could also have binding expressions on them. Is that of interest? Then you would basically write your markup, something like this:

```html
<generate using-model.bind="customer">
  <settings foo="..." bar="..." baz="..."></settings>
</generate>
```

The `settings` element would actually be removed from the DOM and turned into something like a GenerationSettings object (or whatever you specify) and then your `GenerateElement` class would have its `settings` property set to an instance of that with all the data populated. This is something we need for something else we are building and I was thinking of building it into the core for scenarios where elements need to do a lot of config through HTML. What do you think?

**Comment by grofit** [comment]
I did mention in the gitter that I could do the key/value attribute lookup but it wouldnt work for any observables I wanted to resolve, as it would just be a textual resolution.

As far as the settings object I am happy to have a settings property on the class, as this separates the settings object from the underlying class slightly. I had a discussion with @jdanyow about something similar with `@dynamicOptions` as personally it feels a little dirty applying the options directly to the class in that instance as then if you wanted to let something else access these custom options/settings you would need to pass your entire object to it (assuming template generator scenario), whereas if it is just put into its own dictionary style object which is extensible it allows for a lot more flexible plugins for aurelia, especially where the plugin allows devs to extend its underlying features.

Anyway the settings solution seems elegant and then you can have the main/common settings you know about in the normal attributes, but allow for custom extensions underneath it. I guess see what others think as I know this is a niche scenario I discuss but quite a few of my knockout plugins that I want to port over allow custom extensions from other developers, so this would go a long way to help me port them over.

**Comment by atsu85** [comment]
@EisenbergEffect , is the feature you proposed
>
```html
<generate using-model.bind="customer">
  <settings foo="..." bar="..." baz="..."></settings>
</generate>
```
..."and then your GenerateElement class would have its settings property set to an instance of that with all the data populated"

now implemented? I didn't find anything about it from the documentation.

**Comment by EisenbergEffect** [comment]
Something close to that is implemented. We have the `@sync('selector') prop` capability, which creates a property on your class that is synchronized with the dom based on a query selector. However, that creates an array, rather than a single property. Since we need both, I'm t hinking to rename this to `@queryAll('selector') prop` and then to add a new `@query('selector')` as well. This would allow you to select the child element as a property. If it was a custom element, then it's pure ES6 class would be assigned to the variable. So, that would make the above scenario possible. Any thoughts?

**Comment by EisenbergEffect** [comment]
Basically, the idea is that you could do this:

```
@noView
export class Settings {
  @bindable foo;
  @bindable bar;
  @bindable baz;
}
```

```
export class Generate {
  @bindable usingModel;
  @query('settings') settings;
}
```

And this would implement the sample html from above. How does that sound?

**Comment by atsu85** [comment]
Thanks @EisenbergEffect, sound good as long as attribute names of settings (foo, bar, baz) are known at design time, but what if i'd need all attributes? I guess if i needed to read those simple values once (instead of evaluating/binding them to the class that uses them), then i could just inject DOM element and inspect it.

**Comment by EisenbergEffect** [comment]
Yes, in that case, I would recommend to just inject the dom element. You could even be more efficient then that if they were statically defined. You could use `@processContent(yourCustomFunction)` to read the element values at compile time, store them in the compilation instruction, and then have that injected into the constructor. You could them read those values out of a plain JS object.

**Comment by seesharper** [comment]
Would something like this be possible?

`<customelement options="{firstOption:'string literal', secondOption.bind='somepropery'}">`

**Comment by EisenbergEffect** [comment]
You would need to make `options` into a custom attribute. We don't support custom elements with options attributes of their own. But, you can use DI to have the custom attribute injected into the custom element.

**Comment by seesharper** [comment]
Wow, that was fast :) Well, I am not using the @dynamicOptions decorator here. What I am trying to do here is turn the attribute value into a JSON object which I could do by parsing the JSON. But it would be really nice if I also could have binding expressions to work as well. That way the user of my custom element can choose what to specify in HTML as literals and what to bind to the underlying view-model. 

My custom element looks like this 

```
@customElement('monaco-editor')
export class MonacoEditor
{
    @bindable
    public options : monaco.editor.IEditorConstructionOptions;
```

Doing an integration with the Monaco editor for Aurelia :)

**Comment by EisenbergEffect** [comment]
You can't use bindings inside a json object like that but you could do it with a custom options attribute.

```javascript
@dynamicOptions()
export class OptionsCustomAttribute {
  propertyChanged(name, newValue, oldValue) {
    //just a placeholder to be overwritten by the editor
  }
}
```

```javascript
@inject(OptionsCustomAttribute)
export class MonacoEditor {
  constructor(options) {
    this.options = options;
    this.options.propertyChanged = this.onOptionChange.bind(this);
  }

  onOptionChange(name, newValue, oldValue) {
    
  }
}
```

```html
<monaco-editor options="firstOption: string literal; secondOption.bind: somepropery"></monaco-editor>
```

Note that the syntax isn't json but is rather based on the syntax that the `style` attribute uses in native html.

**Comment by EisenbergEffect** [comment]
Another way to do it is to use a normal bindable attribute but just `.bind` it and pass an object literal in.

```html
<my-ele prop.bind="{ prop: 'literal', prop2: binding.expression }"></my-ele>
```

**Comment by EisenbergEffect** [comment]
It depends on what type of api you want.

**Comment by seesharper** [comment]
@EisenbergEffect   Thanks a lot for your help. I really appreciate it :+1:

**Comment by seesharper** [comment]
Works like a charm!!
