### ISSUE TITLE
Knowing if a property is a computed or observable?

### ISSUE THREAD

**Issue by grofit** [aurelia/framework#147]
Coming from the knockout world you have the following functions `ko.isObservable(someProperty)` and `ko.isComputed(someProperty)`. So you can find out if a property of a model is an observable or a computed property (they also have one for observable arrays I think).

I appreciate that in knockout properties are actually knockout observable types so it is far easier for them to check if it is an observable or a computed, however I have a scenario currently where I am traversing a model and need to subscribe to any observables within there, however I cannot find a way to leave out any computed properties. Currently I am just assuming all objects are implicitly observable, but I know this will give me headaches in the long run.

It was mentioned in the gitter that there may be some way to do it with the `observerLocator` (which I am currently trying to use for subscribing to observables), but they (@Aaike) were unsure if it was possible currently.

So could this be thought of as a nice to have?

**Comment by zewa666** [comment]
Computed properties are expressed as JavaScript getters. Thus in order to find out whether a thing is a property you can leverage `Object.getOwnPropertyDescriptor`.

In case of the welcome page in the skeleton navigation app you could do following:

```
constructor() {
  var x = Object.getOwnPropertyDescriptor(Welcome.prototype, 'fullName');
  console.log(x);
}
```

which results in an object like:
```
{ configurable: true, enumerable: true, get: /*the getter function*/, set: undefined }
```

now all you need is to iterate over all props and check for the getter. Now as for the task of listening or getting a list of changes might have a look at the Contacts App's https://github.com/aurelia/app-contacts/blob/master/src/contact-detail.js

There we simply store a JSON stringified version at the begin and check it later with the end-version to determine whether there are changes.

**Comment by grofit** [comment]
I am not sure if the getter check alone would be sufficient as someone could write a getter with a setter, which may be used as an observable which I think could be valid. However given your example I could check to see if there is a get but no set and in that case deem it as a read only property and ignore it.

Would you agree that it is safe to assume that any property which is not a getter/function is potentially an observable? (I have omitted arrays and complex objects as they would end up being traversed for individual properties).

**Comment by zewa666** [comment]
I would say so. Although to be honest I don't see a reason to observe functions/getters at all, since those are just transforming functions of your source, simple class attributes.

**Comment by jdanyow** [comment]
@grofit you might find [this plugin](http://www.danyow.net/introducing-aurelia-computed/) interesting.  It will log messages to the console when aurelia is configured for dev logging.
