### ISSUE TITLE
Add support to `inject` `Document` and `Window`

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/framework#151]
To be able to test classes that depends on Document/Window we need to be able to `inject` them.

**Comment by jdanyow** [comment]
```javascript
container.registerInstance(Document, document);
container.registerInstance(Window, window);
```

:sparkles: :muscle:

**Comment by stoffeastrom** [comment]
:) ofc you can do that but it should be handled by the framework!

**Comment by EisenbergEffect** [comment]
I think we can add this, but in a slightly different way. We might want to have a special symbol for the "global" so that can be independent of the browser. I'm not sure. Need to think about it. (New Metadata release coming has Metadata.global BTW which is the global object independent of platform.)

**Comment by prefinnx** [comment]
Yes, adding this feature would be very helpful for people to play around with Aurelia.

Currently when I want to test code with `jspm run welcome` I get the following error:
```
err  ReferenceError: Error loading "dist/welcome" at file:/Users/gs/agt.prj/healthroe/aurelia/dist/welcome.js
     document is not defined
```

**Comment by EisenbergEffect** [comment]
We have  the pal library to handle accessing these values now.
