### ISSUE TITLE
app.html cannot reverse routes created in app.js

### ISSUE THREAD

**Issue by Nicd** [aurelia/framework#158]
If you create a router in `app.js`, you cannot reverse the routes in `app.html` (the template seems to be rendered before the router is even created). The app will crash, complaining that the route does not exist.

To reproduce:

`app.js` example:
```javascript
export class App {
  configureRouter(config, router) {
    config.title = 'bestsite';
    config.map([
      {route: '', name: 'home', moduleId: './home', nav: false},
      {route: '/login', name: 'login', moduleId: './login', nav: false},
    ]);

    this.router = router;
  }
}
```

`app.html` example:
```html
<template>
  <a route-href="route: login;">Log in</a>
</template>
```

It would be very useful to be able to reverse the routes in `app.html`, to manually create navigation links and such.

This is present in the latest aurelia (0.13.0, and aurelia-router 0.10.0).

**Comment by EisenbergEffect** [comment]
@bryanrsmith This is a bit of a special scenario we need to fix. It may be that we need to put some code in the framework library that detects the route configuration method before the initial root view is created. I'd like to hear if you have any thoughts on this.

**Comment by bryanrsmith** [comment]
@EisenbergEffect That shouldn't be a problem, but I think we'd have to add a framework dependency on router.

Will this cause problems in other places, or could we get away with a little extra logic in route-href? We could probably just check if the router is the root router and is not configured. If so, wait for it to be configured & then run the route generation. Or even a little `whenConfigured()` helper method on the router.

**Comment by EisenbergEffect** [comment]
Actually, I think we could fix this as you say, by ensuring that the `route-href` waits to render the href until after the router is configured. So, the router could have a property indicating whether or not it is configured and also raise a new event when configuration is complete. I think that would do it.

**Comment by bryanrsmith** [comment]
This is actually a different problem than what I originally thought. The issue is that there's no router-view element in the root view. At the moment, the root router is configured when a router-view in the root view registers itself. Since that's not happening, the router config never happens.

I think we can improve the error message, but otherwise the only option is to add a router dependency to the framework and make it configure the root router. 

To work around now, either add a router-view element and hide it or something, or manually configure the AppRouter in the App ctor.

**Comment by bryanrsmith** [comment]
Or I suppose with some minor refactoring, the route-href class could try to configure the router. It might be a little odd, but could work. Will investigate further tomorrow.

**Comment by wshayes** [comment]
This also explains why I couldn't get activate(params) {} to work in the root view.  I was trying to access querystrings in a one-view app which is another use case impacted.

**Comment by EisenbergEffect** [comment]
@bryanrsmith I think we could have the route-href checked the isConfigured property of the router before it does generation. If it's not configured we could have it check the executionContext (which it can get through the bind callback) to see if it has a configureRouter method. If it does, it can run it the same way that other components do and then when that is complete (it may return a promise) perform the generation. How does that sound?

**Comment by bryanrsmith** [comment]
It would work, yes. That configuration step would be required of any component wanting to make use of the root router, though.

The navigation pipeline requires a registered viewport (router-view), right? We may be able to configure the router and generate a route URL, but it doesn't seem like there's much point since we can't navigate to that URL without a router-view to render to. I think we should try to improve the error message, but continue to require that a router-view be present. If it's really the desired behavior, the router could still be configured manually in the view model ctor, or higher up in the app.

**Comment by EisenbergEffect** [comment]
@bryanrsmith I think there probably is a router-view present, but there may be a route-href in the same view with the router-view. It's likely that due to its relative position in the DOM and async nature that the route-href is processing its generation logic before the router-view has a chance to start/finish the router configuration for the associated view-model. I'm just guessing though...

Worse case scenario, I could add logic into the framework startup code that checks for the configureRouter method and runs it. It's a bit of a leak of the router functionality into the framework, but it's livable.

**Comment by Nicd** [comment]
Yes, there is a `<router-view></router-view>` present in the template (I just minimized the example). Its presence does not affect the result.
