### ISSUE TITLE
Problem with getting custom array in sub-repeat

### ISSUE THREAD

**Issue by popovsergiy** [aurelia/framework#176]
This code works fine
```html
<tr repeat.for="item of block.columns.items">
	<td repeat.for="column of [code, name]">
		${column}
	</td>
</tr>
```
but this code nothing show
```html
<tr repeat.for="item of block.columns.items">
	<td repeat.for="column of block.columns.displayed">
		${column}
	</td>
</tr>
```

**Comment by wshayes** [comment]
Hi Popov,

These questions are better over in the Gitter channel: https://gitter.im/Aurelia/Discuss

However, the answer to this is you are in a child scope with the nested repeat.for.  This requires using $parent.block.columns.displayed since it's found in the scope of the outer repeat.for   Without seeing more of the code for the top one, I've no idea how it's working unless you are extracting code and name from item.

**Comment by popovsergiy** [comment]
This really works. Thank you.
