### ISSUE TITLE
LogManager type definition

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/framework#198]
Please add the definition for https://github.com/aurelia/framework/blob/master/dist/aurelia-framework.d.ts#L229.

**Comment by EisenbergEffect** [comment]
Instead `import * as LogManager from 'aurelia-logging'`

**Comment by alexdresko** [comment]
Just a heads up for anyone who lands here, you may have to `jspm install aurelia-logging` for the loader to find that module correctly. At least, that's what I had to do.

**Comment by EisenbergEffect** [comment]
@alexdresko Sorry for the confusion around that! The SystemJS loader can be a little strange in that sense. Sometimes even if you have the module installed, it can't find it because it requires a top level map listing. Explicitly installing forces jspm to add the top level mapping. It's not the design I would have chosen, but that's the way that tool works. Glad you got it working!

**Comment by RichiCoder1** [comment]
Resurrecting this issue as this is rather confusing. If the recommendation is to import `aurelia-logging` as `LogManager`, could the docs [here](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/app-configuration-and-startup/10) be updated? I didn't even realize that was valid.

**Comment by B3zo0** [comment]
@EisenbergEffect 
I'd rather import the log manager from aurelia-framework. If you don't want to support that then please remove that from there or if you want to support it then please add the typing.
