### ISSUE TITLE
Load Performance

### ISSUE THREAD

**Issue by mikeobrien** [aurelia/framework#217]
I've noticed that there is consistently a ~600ms delay between the time the Aurelia bundle is loaded and the app bundle is loaded:

![image](https://cloud.githubusercontent.com/assets/187817/10120694/af6644dc-6496-11e5-9fd4-db0d27de2288.png)

Does that look normal or does it look like there might be a perf issue somewhere? Just looking for a sanity check before digging deeper. That Aurelia bundle is ~500k minified so might make sense.

**Comment by EisenbergEffect** [comment]
We've heard some reports that core-js may be behind this. We aren't sure yet. We would certainly appreciate any findings you could share on the cuase.

**Comment by mikeobrien** [comment]
Sounds good, I'll play with it and see what I can find.

**Comment by EisenbergEffect** [comment]
The summary of this is that some of this was coming from core.js and some from system.js. As a result, we've removed the hard dependency on core-js and added our own minimal set of polyfills. We've also done work to get Aurelia working better with both Webpack and RequireJS-based tools so that there are alternatives to system.js. These seem to solve the issues.
