### ISSUE TITLE
No exceptions shown in browser console when calling non-existing methods in the view

### ISSUE THREAD

**Issue by lobo-tuerto** [aurelia/framework#229]
After upgrading from 0.14 to current (0.17) you can't see exceptions thrown whenever you call a non-existing method in the view.

Just tried with a brand new app with the aurelia/skeleton-navigation and it's the same.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you take a look at this after you get the binding behaviors wrapped up?

**Comment by jdanyow** [comment]
Errors are no longer being thrown because of the changes for https://github.com/aurelia/binding/issues/177 which enable expressions like `${foo.trim()}` where `foo` is potentially null/undefined.

I think we should keep the fixes for https://github.com/aurelia/binding/issues/177 because it makes the behavior consistent with similar scenarios, for example we've always supported `${foo.bar}` where `foo` is undefined.

We should probably restore the behavior where an error is thrown in scenarios where a `call`/`trigger`/`delegate` binding is being invoked.

Thoughts?

**Comment by EisenbergEffect** [comment]
Yes, I think we should probably support the errors for the call/trigger/delegate.

**Comment by jdanyow** [comment]
this was fixed in https://github.com/aurelia/binding/commit/70adcadabcd2bbb93ac595d0cb79235e60c8f4da
