### ISSUE TITLE
Question: accessing custom element VM from nested custom element

### ISSUE THREAD

**Issue by maxgrv** [aurelia/framework#236]
We would like to reach this scenario of nested custom element usage:

      <elementA>
        
        <element B />
        <element B />
       
        <elementC>
            <elementD />
            <elementD />
        </elementC>
        
    </elementA>

where `elementX` are all aurelia custom elements. 

We need each custom element to be able to access the parent custom element VM. At the moment we can achieve this through heavy usage `ref` bindings but it not very nice. We would the elements to auto-wire themselves to the correct parent VM without having to manually specify it.

Is there a way to get to this result?

Thanks

**Comment by stoffeastrom** [comment]
Does [this](http://aurelia.io/docs.html#parent-vm-reference) work for you?

**Comment by EisenbergEffect** [comment]
Yes. If you want to child to get it's parent, simply use Dependency Injection to have the parent injected into the child constructor. Be warned, this will not work if you need to move the child element to a different parent since it's constructor can't be called again to update the parent.

Another way to handle this, which is more versatile, is to give the parent access to its children. To do this you can use the `@sync` decorator, providing a css selector to match. Aurelia will then populate your property with an array of elements that match the selector and keep that synchronized with any dom changes that happen. It would look something like this:

```
export class Parent {
  @sync('child') children;
}
```

All child elements matching the `child` selector would be synchronized into an arry set on the `children` property.

Note: This will change in the next release. `sync` is being renamed `children` and we are also going to add a new decorator: `child` which will simply reference a child element that matches a selector instead of creating an array of matches.

**Comment by maxgrv** [comment]
Thanks Rob, injecting elementACustomElement into elementBCustomElement works perfectly.

We are guaranteed to get the parent instance, not another one, right? Changin the parent is not required in our scenario.

**Comment by jdanyow** [comment]
@maxgrv check out [this answer on stackoverflow](http://stackoverflow.com/a/32781324/725866) for more details on the "inject the parent" approach.

**Comment by maxgrv** [comment]
OK, I was injecting the parent type directly.
