### ISSUE TITLE
Constantly working getter value from view-model to view

### ISSUE THREAD

**Issue by EvgenyKravchenko** [aurelia/framework#25]
Hi, thanks for Aurelia, it looks pretty much!

I found one detail, where I use something like:
```html
<p class="help-block">${fullName | upper}</p>
```
and in view-model getter like this:
```javascript
get fullName(){
  console.log('Looping');
  return `${this.firstName} ${this.lastName}`;
}
```

As result we have some problems with number of invocations of this getter
![screen shot 2015-02-04 at 20 24 53](https://cloud.githubusercontent.com/assets/1778432/6046548/f0321fac-acab-11e4-9935-cc5d57953074.png)

**Comment by jessecogollo** [comment]
Check this in production.  I think this loop is generate for gulp tasks.

**Comment by EvgenyKravchenko** [comment]
Unfortunately, no.

I think there is some problem in dirty-checking.js

In method scheduleDirtyCheck we have timeout for 120 ms...
![screen shot 2015-02-05 at 09 44 08](https://cloud.githubusercontent.com/assets/1778432/6056636/69e7659e-ad1c-11e4-9747-c78475125ec8.png)
...and in invoked method check isDirty check gives result "false", but anyway tracked.length gives "true" and method schedules dirty check again for 120 ms. 
![screen shot 2015-02-05 at 09 48 24](https://cloud.githubusercontent.com/assets/1778432/6056647/9b7cb3b6-ad1c-11e4-8518-b7c9e74d6f2f.png)
So, in such way we have checking every 120 ms - this causes problem I described above.

**Comment by EisenbergEffect** [comment]
Aurelia uses an adaptive binding system. This means we pick the best strategy for observing properties based on how you have defined them and what browser capabilities there are. Additionally, you can plugin in new strategies to teach the binding engine how to handle certain other scenarios. In the case of a "getter" there is no way to observe that. Object.observe cannot observe that and there's no way to generate code to do it. So, we have to fallback to dirty checking.

Dirty checking can basically be implemented in three ways that I know of:
* Polling every so many milliseconds. This is what Polymer does as well as Aurelia, currently.
* Force people to call a "digest" api when they want to dirty check. (Not appropriate for Aurelia since we don't primarily do dirty checking and don't want to force this on users.)
* Monkey patch every async API and event API in the entire DOM. This is what Angular 2.0 is doing with Zones...and it seems extremely intrusive, error prone and could slow down perf for all these APIs.

Ultimately, we will have an API for declaring computed properties so that the system won't need to fallback to dirty changes for these types of scenarios. We don't have that yet though. If you have ideas on how to improve this, we'd love to hear them.

**Comment by EisenbergEffect** [comment]
Note, if the value is the same as before...it shouldn't actually be updating it in the view. If it is, that's a bug. It should only be checking it.
