### ISSUE TITLE
view gets loaded before previous view is deleted

### ISSUE THREAD

**Issue by pranayvermado** [aurelia/framework#263]
HI,

In my application I recently updated to beta 1.03, and I noticed there is one issue that is 
on navigating the view gets loaded before the current view get deleted. so its look like as shown in attached screen shot.
![view](https://cloud.githubusercontent.com/assets/5179806/11650121/28ec7d46-9dac-11e5-9f02-22ffe7ee11d7.png)

so here Github user is my current view and then i navigate to welcome view so this is how its loading in 

1.0.0-beta.1.0.3 but in just previous version its working fine.

**Comment by EisenbergEffect** [comment]
You can fix this by setting `swap-order="after"` on the `router-view` element in html. This controls the order and timing that the `router-view` swaps from one view to another. I think we should make the default swap order "after" in the next release in order to prevent these unexpected issues, though more advanced animations, involving both views, will usually use today's default of "before".

@joelcoxokc Should we change the default mode to "after" or do you think we should somehow change the skeleton's default animation to take advantage of "before". What would be involved with that? Is it a fairly simple CSS animation fixup?

**Comment by joelcoxokc** [comment]
The default should be `after` I'll make a pr
