### ISSUE TITLE
Aurelia and Observables for http calls

### ISSUE THREAD

**Issue by thelgevold** [aurelia/framework#269]
I personally really like promises, and from what I can tell, Aurelia seems to go in the direction of a promise based http client. 

However, with the all the talk of Observable based http libraries (Angular 2.0), is there any talk of incorporating an http client based on Observables? 

I am assuming you can just bring in any Reactive library and incorporate it yourself, but am interested in hearing the thought of the Aurelia community on this.

Thanks

**Comment by EisenbergEffect** [comment]
I'm not sure that the Observable interface makes sense for HTTP. It would make sense more for a real-time API. Right now, we are basing our HTTP client on the new Fetch specification, which is itself based on the Promise specification. So, in this was we are trying to stay close to the standards. If we were to build a real-time API, I do think it would make sense to base that on the Observable.

**Comment by thelgevold** [comment]
@EisenbergEffect 
Thanks for your reply!

I have more visibility in the Angular 2 community, but I do play around with Aurelia as part of my Blog/POC work . I actually agree with you on this one since I don't see enough real use cases for observables when it comes to http. 

I always find it interesting to see the reasoning behind architectural decisions in frameworks though, so I actually asked the opposite question to the Angular guys. 

Here is the discussion in case you are interested: https://github.com/angular/angular/issues/5876

**Comment by EisenbergEffect** [comment]
It's important to have the proper abstractions. When it comes to http, I think of Fetch as the low level network access in this case. So, that doesn't have a notion of "retry" built-in for example. It's just a single request/response api. That makes sense to be based on Promises, just as the Fetch spec is. Now, if you wanted to build something on top of that that made more sense for Observables, you can do that because you can adapt a Promise to an Observable. But, that would be a higher level API.

It's important to consider SoC in these cases.

In the issue above there's the mention of a "type ahead" control. But this is a UX paradigm, not a networking idea. So, while it might be easier to handle the event orchestration of the user at the UI level with an Observable, that should not be confused with the network calls, which are independent and don't have the same relationship to the user interaction necessarily.

**Comment by thelgevold** [comment]
Yeah, I think that is a good point. A request/response api typically represents the 90% use case in most applications. There have been times when I've had to incorporate retries with promises, but it was a one off tied into a specific business case where I made my own abstraction.

**Comment by benjamingr** [comment]
Reading: https://groups.google.com/forum/#!topic/angular-data-dev/AdULPprCkbI%5B1-25%5D
