### ISSUE TITLE
aurelia-framework is not providing the decorators function

### ISSUE THREAD

**Issue by darkelyte** [aurelia/framework#271]
In the [Getting Started](http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.0.3/doc/article/getting-started) docs, in `ES 2015` mode, the nav-bar section shows the following code:
```
import {bindable, decorators} from 'aurelia-framework';

export let NavBar = decorators(bindable('router')).on(class {
  constructor() {
    this.router = null;
  }
});
```

When running this code, the console displays the error:
`decorators is not a function`

In order to get the `decorators` function to work, it must be imported from `aurelia-metadata`, which in turn must be added to the `map` section of `config.js`.

Either the documentation is wrong, or `aurelia-framework` is not providing a proper `decorators` function.

**Comment by EisenbergEffect** [comment]
We believe this is a bug in Babel's transpilation of system.js. We are looking into it.

**Comment by Gheoan** [comment]
`DOM` is also not exported.

```javascript
import { DOM } from 'aurelia-framework';
console.log(DOM); //undefined
```

**Comment by EisenbergEffect** [comment]
You can get it from 'aurelia-pal' for the mean time.
It is actually exported. https://github.com/aurelia/framework/blob/master/src/index.js#L8
That it isn't available, we believe is a bug in Babel.

**Comment by vinhtq** [comment]
+1 So how can i go over this bug. Is there any work around?

**Comment by EisenbergEffect** [comment]
You can get decorators from 'aurelia-metadata'. You may need to jspm install aurelia-metadata first.

**Comment by vinhtq** [comment]
Thanks! I suggest we should put this anwser somehow in the guide. Because i have many problems when i start

**Comment by jhoguet** [comment]
I also ran into this with `metadata`. 

I dug deep enough to find that the following [line](https://github.com/aurelia/framework/blob/master/dist/commonjs/aurelia-framework.js#L408) of generated code is not doing what you would expect 

```js
_defaults(exports, _interopExportWildcard(_aureliaMetadata, _defaults));
```

`_aureliaMetadata.metadata` contains what I want, but after this line of code executes, `exports.metadata` does not. 

Digging deeper, I find the following [function](https://github.com/babel/babel/blob/e604bf229b65f5f87fcc11ae51bd048305e68903/packages/babel-helpers/src/helpers.js#L130) doing something suspicious. 

```js
function _defaults(obj, defaults) {
    var keys = Object.getOwnPropertyNames(defaults); 
    for (var i = 0; i < keys.length; i++) { 
        var key = keys[i]; 
        var value = Object.getOwnPropertyDescriptor(defaults, key); 
        if (value && value.configurable && obj[key] === undefined) { 
            Object.defineProperty(obj, key, value); 
        } 
    } 
    return obj; 
}
```
where `Object.getOwnPropertyDescriptor(defaults, 'metadata').configurable` returns false causing it not to copy the value over. 

Not sure why it is `false` or why `_defaults` does not want to copy properties which are not `configurable`. 

My work around was to `jspm install aurelia-metadata`  and import `metadata` from `aurelia-metadata` instead of from `aurelia-framework`. 

Hope that helps...

**Comment by EisenbergEffect** [comment]
Thanks for investigating this. It appears to be a bug in the compiler. We are hopeful that when we update to Babel 6 this will be resolved.

**Comment by jhoguet** [comment]
Looks like this is [not fixed](https://github.com/babel/babel/blob/6.4-stable/packages/babel-helpers/src/helpers.js#L136) and I couldn't find any reference to a known issue, so [I logged one](https://phabricator.babeljs.io/T7102).

**Comment by EisenbergEffect** [comment]
Thanks for following up on that!
