### ISSUE TITLE
Can not load component in chrome packaged app

### ISSUE THREAD

**Issue by alisabzevari** [aurelia/framework#278]
I am writing a chrome packaged app (not extension) with aurelia, typescript, materializecss and jspm.
I have bundled my application using `jspm bundle` and loaded in page using CSP version of systemjs. Everything works but loading my first app component failed with this error:
```
Uncaught SyntaxError: Unexpected token <
Unhandled promise rejection Error: chrome-extension://hcaaohffobameoipfhinikkfmkjjdfgi/app.html!text did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
	Error loading chrome-extension://hcaaohffobamkjipfhinikkfmcejdfgi/app.html!text
	Error loading chrome-extension://hcaaohffobamekjpfhinikkfmcejdfgi/app.html!template-registry-entry
    at HTMLScriptElement.f (chrome-extension://hcaaohffobamekjpfhinikkfmcejdfgi/jspm_packages/system-csp-production.js:4:25869)
```
You can see my source code [here](https://github.com/alisabzevari/Teatr/tree/chrome-app)
Any ideas?

**Comment by EisenbergEffect** [comment]
I haven't used the CSP version of system.js so I'm not familiar with its actual differences in implementation. Does it have any limitations?

The error you are getting is as if the view is being parsed as javascript instead of text. I'm not sure about using jspm bundle directly either. Have you tried the aurelia-bundler?

For future assistance, please ask this question in the gitter channel: gitter.im/aurelia/discuss
