### ISSUE TITLE
Update Core-JS Dependency

### ISSUE THREAD

**Issue by AStoker** [aurelia/framework#282]
Core-JS has been updated to version 2.0 (https://github.com/zloirock/core-js/releases/tag/v2.0.0). In it there are fixes for TFS users who cannot commit files that have `$` in the name (and as a result could not commit core-js files to the server). 

Currently, Aurelia is referencing v1.2.6 of core-js. Please upgrade the reference (assuming tests pass) to v2.0.

**Comment by AStoker** [comment]
As a note, I manually upgraded my references in package.json and config.js to use the 2.0 version of core-js without any troubles.

**Comment by MrAndMrsK** [comment]
@AStoker - when I attempt this find-and-replace of `@1.2.6` to `2.0.0` in `package.json` and `config.json` with a fresh download of the typescript skeleton (for example) `npm install` still ends up getting the old version of core-js because the eventually downloaded dependencies within each individual Aurelia package references that old version.  So must we find and replace AFTER `npm install` in all the dependencies as well (and before attempting to put them in TFS-control) and carefully never run `npm install` again?

Is there a workaround for now to override the version resolution of all dependencies from 1.2.6 to 2.0.0?  I tried to use variations on `"jspm" : { ... "overrides" : { "aurelia-*" : { "dependencies" : { "core-js@1.2.6" : "core-js@2.0.0" } } } }` as I failed to find documentation about jspm overrides - and my guesses didn't work either.  Also, I don't fully understand the difference between `npm install` and `jspm install` and when it's correct to use one vs the other and whether `npm install` does everything that `jspm install` does plus some devDependencies??

Actually, if I could rip out the core-js dependency all together I would and include shims only for the features that my target browser doesn't support.  Is there ALSO a way to override subdependencies to NOT depend on core-js at all?

Thanks!

**Comment by EisenbergEffect** [comment]
You can always remap core-js to an arbitrary module that contains only what you want.

**Comment by AStoker** [comment]
@MrAndMrsK, it would help if you install (with jspm) the version 2.0 of core-js, that way any other dependency that just says it needs core-js will use 2.0. THEN, you will also have to change the `config.js` file to modify the dependencies to all use v2.0 of core-js. At that point, running `jspm install` should look at all those changes you just made and use the 2.0 version and not download 1.2.6. If you ran `jspm update` or something that goes to the server to look for new versions, it will most likely revert your changes back to 1.2.6 and you will need to change those back to 2.0 again.  

NPM and JSPM are different. For our system, NPM is used more for server side code, such as compilation, and JSPM is used for front end code, such as bootstrap or aurelia. There's no real reason why you couldn't just use NPM across the board, but JSPM does make it easier to access other kinds of libraries for code (NPM typically, but not always, contains more Node based packages which don't run on a website, but rather the server itself). That's my observation on it at least.

I've not had any luck with overrides, and I believe it would essentially be doing the same thing I just mentioned, and would be reverted in the same instances. 

As Eisenberg mentioned, you could remap to your own version of core, or anything else for that matter, but simply modifying the definition of core-js in the `config.js`. Something like this would probably do it:
``` javascript
"map": {
    ...
    "core-js": "path:some-other-library@1.0.0",
    ...
}
```

**Comment by MrAndMrsK** [comment]
@AStoker - that's really helpful confirmation and new info, thanks!

**Comment by EisenbergEffect** [comment]
All done...
