### ISSUE TITLE
self closing form of templates results next element being removed

### ISSUE THREAD

**Issue by cjdibbs** [aurelia/framework#283]
using the following code:
```html
<require from="poker-card.html" ></require>
...
<poker-card ... />
<div id='cookie'>
    <span>${myself.name}</span>
</div>
```
results in the div#cookie to be eaten by some monster, clearly I should use the non-self closing form of the tag (which works with out issue)

I would suggest either fixing it so you can use a self closing form, or making it so that the build process will throw an error.

**Comment by EisenbergEffect** [comment]
There is no such thing as custom self-closing tags in HTML. The spec defines that only certain, special HTML element can be self-closing. It's beyond the power of any framework to change this since it's part of the HTML spec and enforced by the browser itself.

It is conceivable that we could try to add something to our bundler to check this...but it would involve bringing in a full spec-compliant HTML parser. I'm not sure if we want to do that just for this use case now. However, there are other things in the future that we might add that for, so this is something we could consider if others want it later down the line.

Best thing to know is that self-closing elements aren't allowed outside of the ones defined by the spec.
