### ISSUE TITLE
Firefox 43.0.2 if.bind and repeat.for bug

### ISSUE THREAD

**Issue by Aniel** [aurelia/framework#293]
In Firefox 43.0.2 the following doesn't work:
ViewModel:
```javascript
export class MyViewModel {
    items = [
        {
            show: true,
            title: "1"
        },
        {
            show: true,
            title: "2"
        }];
}
```

View:
```html
<h1>Result</h1>
<ul>
  <li repeat.for="item of items" if.bind="item.show">
      ${item.title}
   </li>
</ul>
```

In chrome the result is the following:
![image](https://cloud.githubusercontent.com/assets/4410553/12301123/c150f0f6-ba1e-11e5-9cc9-334bc53ebc07.png)

In Firefox 43.0.2 (Newer versions work fine)
![image](https://cloud.githubusercontent.com/assets/4410553/12301191/08805c28-ba1f-11e5-8650-c33a879639c2.png)

**Comment by Gheoan** [comment]
Possible duplicate: https://github.com/aurelia/templating-resources/issues/111#issuecomment-171087593

**Comment by vinhtq** [comment]
+1 Not working for me also. And also on opera

**Comment by EisenbergEffect** [comment]
Closing since it's a duplicate. You can't have if and repeat on the same element. Should the repeat be ifed? or should the item be ifed? That cannot be determined since browsers don't always preserve the attribute order. The solution is to nest the template elements the same way you would nest if and for blocks in JS.
