### ISSUE TITLE
Can't import aurelia files with jspm@0.17.0

### ISSUE THREAD

**Issue by Secbone** [aurelia/framework#305]
I update my jspm to 0.17.0,  then I found the System get the wrong url of aurelia packages,like this:
```
/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.0.2/aurelia-bootstrapper.js
```
and the right url path is:
```
/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.0.2/dist/amd/aurelia-bootstrapper.js
```

**Comment by cehoffman** [comment]
The first path is actually correct. The problem comes from jspm 0.17 changing the key in the directories configuration from `lib` to `dist`. You can get around this temporarily by setting an override of the form `{"directories": {"dist": "dist/amd"}}` for each aurelia package.

It is really painful to do manuall, so I just wrote a script using `jspm/api` to parse out all aurelia packages and set the override.

**Comment by EisenbergEffect** [comment]
0.17.0 is in Beta and is not released or recommended except for testing purposes. It has many breaking changes and is not yet supported by Aurelia. That said, we've been talking with the JSPM team about how to migrate in a backwards compatible way so that we can support the current released version and the beta. We'll be doing that in the near future.
