### ISSUE TITLE
VM Model Binding Changed in Beta 1.1.x

### ISSUE THREAD

**Issue by MarkHerhold** [aurelia/framework#311]
It seems that there has been a breaking change between Beta 1.0.x and 1.1.x in regards to child VMs binding to values and calling functions on a parent VM that is repeating over elements. It is my understanding that there were not supposed to be breaking changes in the new 1.1.x beta version.

I have created two plunkrs, each with the same code (`books.js`, `books.html`, `book.js`, `book.html`) but different configs to point to the respective beta versions.

Here is the working plunkr with Aurelia 1.0.x (forked from jdanyow's plunkr):
http://plnkr.co/edit/sbt4uPmrpsBOBhtuovjr

Here is the broken plunkr with Aurelia 1.1.x:
http://plnkr.co/edit/Mb6rSrC9GMqWpiMLEiij

Things that appear to be broken:
* The book object that is repeated over in `books.html` does not appear to be bound to the book element, resulting in empty remove buttons.
* The book element is unable to call a function on the parent VM, `removeBook(bookName)`

Please let me know if what I am doing is no longer expected to work or supported, and the "recommended" way to approach this simple scenario.

**Comment by EisenbergEffect** [comment]
There may have been a regression. @jdanyow Can you take a look?

**Comment by jdanyow** [comment]
In previous releases there was a bug that allowed custom element templates to access the outer scope.  Fixing this bug is what's causing your issues.

The `book` element's template looks like this:

**book.html**
```html
<template>
  <button type="submit" click.delegate="removeBook(book.name)">remove ${book.name}</button>
</template>
```

And it's view model looks like this:

**book.js**
```js
export class Book {
}
```

This will not work, it creates a situation where the `<book>` element can only be used when the outer scope implements a certain interface (removeBook and book). Compare this with a `div`, `a`, or `p` element... these can be used anywhere.

There's a couple ways to fix this.  

#### Option 1: Add bindables to your custom element view-model

The correct way to get data into a custom element is via bindable properties.  Change book.html and book.js to this:

**book.html**
```html
<template>
  <button type="submit" click.delegate="remove()">remove ${name}</button>
</template>
```

**book.js**
```js
import {bindable} from 'aurelia-framework';

export class Book {
  @bindable remove;
  @bindable name;
}
```

Then it's usage changes from `<book></book>` to:

**books.html**
```html
...
<book remove-book.call="remove(book.name)" name.bind="book.name"></book>
...
```

#### Option 2: remove the book.js viewmodel and use compose:

**books.html**
```html
...
<compose view="book.html" model.bind="book"></compose>
...
```

**Comment by MarkHerhold** [comment]
Makes sense. I rather liked the flexibility of the scope bug though.  ;)

Thanks for the detailed response on the proper way™ to do things.
