### ISSUE TITLE
Interpolation binding triggers unnecessary expression evaluation

### ISSUE THREAD

**Issue by djoooooe** [aurelia/framework#334]
to reproduce, download the current navigation-skeleton (commit e2705e8faf4baf5993a005a0f425e05f78640fab) and log something to console everytime fullName() is executed with @computedFrom on. 
I suspect that either computedFrom is triggering two executions of the getter on every change, or the change handlers are firing two events.

**Comment by jdanyow** [comment]
https://gist.run/?id=e12b5973ff2871cc31c8

**Comment by jdanyow** [comment]
The first property-getter access happens when the binding evaluates the expression during the initial bind, to assign the model value to the element.

The second property-getter access happens when the binding "connects" the expression (sets up the observers).  The observer grabs the current value because it needs the `oldValue` when it fires change events.

I couldn't find a way to eliminate either of the accesses without making significant changes.

**Comment by djoooooe** [comment]
In that case I would suggest to at least add a warning to the docs, since this behavior does have a big performance impact when developers decide to put CPU-intensive computations inside the getter.
