### ISSUE TITLE
bidirectional value converter (sometimes) doesn't update view

### ISSUE THREAD

**Issue by ariovistus** [aurelia/framework#341]
here: http://plnkr.co/edit/cEY805
I have a naive number formatting value converter applied to an input. it mostly works, except in this scenario:

model value = 0 view value = "0.00"
user changes view to "0"
on blur, model remains 0 and view remains "0"

I was hoping for the view to change back to "0.00". I can work around it easily enough with a blur event, but is this behavior what I should be expecting from aurelia?

**Comment by jdanyow** [comment]
hi @ariovistus, yes this is the correct behavior.  The binding system will update the view only when the model value changes.  When the model value is already zero and you make a change to the input that would be converted to zero, there's no model property change, which is why you don't see the input's value become formatted. I tested this in the latest version of Aurelia, same result:
https://gist.run/?id=42db54d1bd6ae620fdab
