### ISSUE TITLE
Consider exposing `.d.ts` in top level declaration

### ISSUE THREAD

**Issue by unional** [aurelia/framework#360]
Current they are wrapped in `declare module "aurelia-framework" {`
It is actually not needed and can be exposed as top-level declaration instead.
https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#23-declarations

It's the same format `tsc` expose.
With that format, you can expose the typings through `package.json/typings` property and IDE (e.g. vscode) can pick it up.

Also, top level declaration will be compatiable with [`typings`](https://github.com/typings/typings).

**Comment by unional** [comment]
Actually exposing them in two formats. The current one can be consumed directly (e.g. used by WebStorm).

The top-level declaration on for `TypeScript language service` (used by vscode and Visual Studio, and atom?). expose that through `package.json/typings`

**Comment by atsu85** [comment]
@unional, **I don't think there are any reasons to change current format how TypeScript declarations are generated for Aurelia**, or add another "unwrapped format". I guess Your IDE is incorrectly configured and therefore results problems for You. I haven't ever had any problems with Atom and Aurelia TS declrations, and I'll bet that there are no such problems with other IDEs either - otherwise these problems would have manifested almost year ago.

TypeScript documentation articles [modules](http://www.typescriptlang.org/docs/handbook/modules.html), [namespaces (formerly known as internal modules)](http://www.typescriptlang.org/docs/handbook/namespaces.html) and [Namespaces and Modules](http://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html) are worth reading to understand the subject in depth.

I suspect that part of the confusion might be caused by namespaces (aka internal modules) vs modules (aka external modules):
1) what is the difference in generated code
2) how type definitions are written for them
3) how to reference the definitions (either from the file or tsconfig.json)

For example, one potential source of confusion could have been follwoing from the [modules documentation](http://www.typescriptlang.org/docs/handbook/modules.html):
> # Guidance for structuring modules
> ## Export as close to top-level as possible
> Exporting a namespace from your module is an example of adding too many layers of nesting. While namespaces sometimes have their uses, they add an extra level of indirection when using modules. This can quickly becomes a pain point for users, and is usually unnecessary.

and 
> #Do not use namespaces in modules
> When first moving to a module-based organization, a common tendency is to wrap exports in an additional layer of namespaces.

The point there (as I understand) is:
If You are writing TS declarations for module in external module format (now simply called as module, that is javascript packaged as AMD, CommonJs, UMD, or System), then You shouldn't use `namespace` keyword (or former `module` keyword, that is now deprecated in favor of `namespace`) , that is not meant for modules (external module format), but for internal module format (now known as namespace). The reason is that with (external) modules variables can't pollute global namespace unlike with internal module format. For that reason it doesn't make sense to add extra "wrapper" around already "wrapped" code.

**Comment by unional** [comment]
First of all, thank you for taking time to write your response.

I think you misunderstand what I said. I'm proposing to unwrap it from `declare module "aurelia-framework" { }`. You can check out any typings repos in https://github.com/typed-typings
These are typings that expose module in top-level declaration format.

It is the same format exposed by tsc if the code is written in TypeScript and generated by `tsc -d`.

**Comment by unional** [comment]
By the way, you can try it out yourself. Go to `./node_moudules/aurelia-framework` and edit the `aurelia-framework.d.ts` file like I said, it is pretty simple.
It will work on Atom too.

**Comment by unional** [comment]
Also, this might help you to understand it a little better:
https://github.com/typings/typings/blob/master/docs/external-modules.md

**Comment by unional** [comment]
> The point there (as I understand) is:

One more point to make is that the TypeScript handbook have not (yet) clearly address the downside of having `declare module "abc" {` wrap. There are numbers of issues I'm involved in TypeScript and you can look it up to understand it better. :rose:

Good job in reading the docs thou. :+1:

**Comment by atsu85** [comment]
@unional, thanks for quick response
> TypeScript handbook have not (yet) clearly address the downside of having declare module "abc" { wrap

Now i understand the downside. It really didn't occur to me when reading the official TypeScript documentation from the website. I should have read more Typings docs than just usage and upgrade from TSD. 

Sorry for the confusion, and thanks again for educating me :)

**Comment by unional** [comment]
You are welcome. It is not simple to understand. :+1:

**Comment by EisenbergEffect** [comment]
Can someone summarize for us what we should do going forward?

**Comment by unional** [comment]
@EisenbergEffect sorry for the late reply.

Are the users relying on `tsc` to load the typings? If they are, then the action item is simple: Just remove the `declare module "aurelia-framework" {` wrapping.

If there are users who use it through `/// <reference path="node_modules/aurelia-framework/aurelia-framework.d.ts" />`, then the situation is more complex as TypeScript 2.0 might have some changes. AFAIK, you need to do this instead:
- create another file (e.g. `aurelia-framework-module.d.ts`) which has the wrapping removed.
- Set `package.json/typings`: "aurelia-framework-module.d.ts"

Just to double check, @blakeembrey, does this look right?

**Comment by EisenbergEffect** [comment]
Ok, so we need two d.ts files, one for each usage scenario, but we need the unwrapped on linked from our package.json files. Is that correct @unional 

@cmichaelgraham Can you look into this? It looks like changes in the TS ecosystem that we need to account for. We'll need to change our build processes.

**Comment by blakeembrey** [comment]
@unional LGTM. You won't need Typings at all if the whole dependency tree switches to the module format. From the TypeScript docs on providing typings: https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by EisenbergEffect** [comment]
All libraries converted over to use the `typings` field of the `package.json` with d.ts file formats properly updated.
