### ISSUE TITLE
Custom attribute not setting value if @bindable present

### ISSUE THREAD

**Issue by grofit** [aurelia/framework#392]
## Scenario

So the scenario is I have a custom attribute which I would expect users to use in one of two ways.
### Shorthand

`<div some-attribute.bind="someVal">...</div`

So this way the user would use it without having to set any internal properties for the attribute and generally the cleanest way of expressing the intent.
### With additional options

`<div some-attribute="property1.bind: someVal; property2: someLiteral">...</div>`

This way the user sets the same value as the shorthand in the `property1` section however can also add `property2` which would provide some additional information, this is a simple example but there could be more than 2 more properties, however they would all be known at time of writing so it would not really be dynamic options as such.
## Problem

So the problem here is trying to support both the simple `this.value` which is set if you have no `@bindable` and is set to the correct expression. However if I were to add a `@bindable` in, be it at class level or on top of each internal property:

```
@bindable({ name: "property1", attribute: "property1", ...}
export class SomeAttribute {...}
```

and

```
export class SomeAttribute
{
   @bindable property1;
}
```

So if I were to have no `@bindable` decorators, then the `this.value` would be passed through and the short hand would work. However if I then add code for the second scenario, then I cannot do the shorthand way as `this.value` is always undefined, so it seems I can only support the shorthand OR the longer way, not both.

So is this a bug or as intended?
## Some acceptance criteria the way I see it

**Given** I have a custom attribute
**And** it has no bindable properties
**When** I pass it an expression `someVal`
**Then** the attribute property `value` should equal `someVal`

**Given** I have a custom attribute
**And** it has a bindable property called `property1`
**And** it has a bindable property called `property2`
**When** I pass it an expression `someVal`
**Then** the attribute property `value` should equal `someVal`
**And** the attribute property `property1` should be null / undefined
**And** the attribute property `property2` should be null / undefined

**Given** I have a custom attribute
**And** it has a bindable property called `property1`
**And** it has a bindable property called `property2`
**When** I pass it an internal property `property1` with binding `someVal`
**And** I pass it an internal property `property2` with literal `"someLiteral"`
**Then** the attribute property `value` should equal null / undefined
**And** the attribute property `property1` should equal `someVal`
**And** the attribute property `property2` should equal `"someLiteral"`
## End blurb

So is there a way to satisfy the above criteria, so I can support both use cases from a single class?

**Comment by EisenbergEffect** [comment]
Today, it is intentional that you either have a basic attribute or an options attribute. An options attribute can't function with a simple value. However, we would like to add this in the future. We have a use case for it inside Aurelia with our route-href attribute.

That said, I don't think we'll have time to implement this ourselves for v1. I think it could be done in a point release thereafter pretty easily without breaking anyone's code. If you had time to implement it and send a PR, we might be able to squeeze it in ;) I'll be honest though...I haven't thought about the best way to implement it myself, and unfortunately, I don't have any time to advise you right now. If you want to take a crack at it, we can review and go from there.

I think we might just want to designate one of the bindables as the "default" or use the first bindable. So, if there aren't options, but rather a simple value, then one of the existing bindables gets set with that value, the one designated as the default. Thoughts?

**Comment by EisenbergEffect** [comment]
Important note, most of this feature might actually need to be implemented in the syntax parser itself. @jdanyow @martingust @AshleyGrant You guys have any thoughts on the above?

**Comment by grofit** [comment]
Thanks for the info, currently I don't know the aurelia code base well enough (I have barely used Aurelia to date) so I wouldn't feel comfortable jumping in and trying to alter the main parsing functionality for this.

I have not tried `@dynamicOptions` I assume this would yield same issues, but its not the end of the world for me, it's just I would rather have shorthand methods for consumers of the attributes rather than having to put in the longer stuff.

Anyway will keep an eye on this and see what the other guys think on this scenario.

**Comment by EisenbergEffect** [comment]
I think we definitely want to support this. It just might have to wait a bit until we tackle a few other things.

**Comment by jdanyow** [comment]
Would it make sense to introduce the ability to declare one of the bindable properties the "default" or "primary"?  Instead of using `value` OR `property1` and `property2` we could declare `property1` as the primary bindable.  Then `property` could be bound using the shorthand or options syntax.  I think this would simplify the code a developer needs to write.

**Comment by grofit** [comment]
that would work just as well for me, if anything that would be more consistent too, as the way I mention you have to check if `this.value` exists then use it etc, but if you just have a default property then it streamlines logic and takes less "magic" out of the process.

**Comment by EisenbergEffect** [comment]
@jdanyow We definitely need to keep `value` if there are no bindables, but if there are bindables, I think being able to declare one the default would be nice. Then we could support what @grofit is looking for.

**Comment by Alexander-Taran** [comment]
stale since april 2016

**Comment by StrahilKazlachev** [comment]
I think that the `primaryProperty` option covers this issue, mostly.
@bigopon what do you think?

**Comment by EisenbergEffect** [comment]
Yep, this is now implemented.
