### ISSUE TITLE
Event Aggregator within Filereader onload method with Aurelia 

### ISSUE THREAD

**Issue by genericuser-me** [aurelia/framework#420]
this.eventAggregator does not gets its value within onload function. Even the way below isnt working. I need the filereader object to get the binary string of the selected file. 
```
var reader = new FileReader();
      var binArray; 
      var eventAgg = this.eventAggregator;    
      reader.onload = function () {               
                binArray = reader.result;
                eventAgg.publish(new evt.FireEvent);
         };
      reader.readAsBinaryString(this.selectedFiles[i]);
```

**----------------------------------EDIT-----------------------------------------------**

Modified the code from what I posted above. Adding the whole code, overall, the problem remains the same as mentioned above.

**View:**
`<input type="file" files.bind="selectedFiles change.delegate="getFiles()">`

**ViewModel**
```
 GetReaderFilesAsync(file, callback): any {
        var reader = new FileReader();
        reader.onload =  function () {          
            var bArray = reader.result;
            callback(bArray, eventAgg);
            
        };
        reader.readAsBinaryString(file);          
    }

getFiles()
{
var eventAgg = this.eventAggregator;
  for (let i = 0; i < this.selectedFiles.length; i++) {
this.GetReaderFilesAsync(this.selectedFiles[i], function(val, eventAggr) {
                 eventAggr.publish(new Events.FileEvent());
}

}
```

**Comment by AshleyGrant** [comment]
`evt` isn't defined in your code

**Comment by AshleyGrant** [comment]
Here's the code I have showing it working:

*app.js*
```javascript
import {inject} from 'aurelia-framework';
import {EventAggregator} from 'aurelia-event-aggregator';
import {FileEvent} from 'file-event';

@inject(EventAggregator)
export class App {
  constructor(ea) {
    this.ea = ea;

    this.ea.subscribe(FileEvent, (event) => {
      console.log(`Event received in app.js`);
      console.log(event);
    });
  }
  configureRouter(config, router) {
    config.title = 'Aurelia';
    config.map([
      { route: ['', 'upload'], name: 'upload',      moduleId: 'upload',      nav: true, title: 'Upload' }
    ]);

    this.router = router;
  }
}
```

*upload.js*
```javascript
import {inject} from 'aurelia-framework';
import {EventAggregator} from 'aurelia-event-aggregator';
import {FileEvent} from 'file-event';

@inject(EventAggregator)
export class Upload {
  heading = 'Welcome to the Aurelia Navigation App!';

  constructor(ea) {
    this.ea = ea;
  }

  getReaderFilesAsync(file, callback) {
    const reader = new FileReader();

    reader.onload =  () => {
      const bArray = reader.result;
      callback(bArray);
    };

    reader.readAsBinaryString(file);
  }

  getFiles() {
    for (let i = 0; i < this.files.length; i++) {
      const file = this.files[i];
      this.getReaderFilesAsync(file, (val) => {
        this.ea.publish(new FileEvent(val));
      });
    }
  }
}
```

file-event.js
```javascript
export class FileEvent {
  constructor(val) {
    this.val = val;
  }
}
```

**Comment by genericuser-me** [comment]
Its under a custom element. Sorry missed that in initial code. I am still getting:

"content-menu.ts:193 Uncaught TypeError: Cannot read property 'publish' of undefined"

**Comment by AshleyGrant** [comment]
The fact that it's in a custom element isn't causing the issues you're seeing.  The issues you are seeing are likely because you are passing the `EventAggregator` instance around as function parameter. It is a property of your class, so you can simply access it via `this` like I am in my code. Not that I'm using fat arrow/lambda functions in my code to make `this` mean "the class instance."

Try modifying your code to more closely match mine and it should clear up the issues you're seeing.

**Comment by AshleyGrant** [comment]
Let me explain better:
```javascript
 GetReaderFilesAsync(file, callback): any {
        var reader = new FileReader();
        reader.onload =  function () {          
            var bArray = reader.result;
            callback(bArray, eventAgg);

        };
        reader.readAsBinaryString(file);          
    }

getFiles()
{
var eventAgg = this.eventAggregator;
  for (let i = 0; i < this.selectedFiles.length; i++) {
this.GetReaderFilesAsync(this.selectedFiles[i], function(val, eventAggr) {
                 eventAggr.publish(new Events.FileEvent());
}

}
```

The problem is that you are passing `eventAggr` as a parameter to the callback function in `GetReaderFilesAsync`, but you aren't setting the value of the parameter in `GetReaderFilesAsync`. When you call `this.GetReaderFilesAsync`, you pass the file object and a callback. In `GetReaderFilesAsync`, you call the callback function with two parameters, `bArray` (which is set on the line above the call) and `eventAgg` (which is being instantiated as null in the call).  `eventAgg` *doesn't exist* and so you are basically doing this:
```javascript
var bArray = reader.result;
callback(bArray, null);
```

And the runtime is telling you that a null reference doesn't have a function called `subscribe`.

Just switch to using fat arrow/lambda functions and use `this.eventAggregator` in the callback like I did.

**Comment by genericuser-me** [comment]
I had initially used `this.eventAggregator`, but was still getting the same error, so tried the other way around.

**Comment by AshleyGrant** [comment]
Yes. `this.eventAggregator` won't work for you unless you use fat arrow functions.

**Comment by genericuser-me** [comment]
My bad! missed the fat arrow. It is not giving error, though fileEvent is not getting called .

**Comment by genericuser-me** [comment]
![image](https://cloud.githubusercontent.com/assets/17732922/15280051/9a08030e-1af9-11e6-958f-01e24dfe4f44.png)

Still undefined.

**Comment by genericuser-me** [comment]
No error, everything is fine. But the subscribe is not called.

**Comment by AshleyGrant** [comment]
Would it be possible for you to ping me on Gitter? I can possibly help you better there.

**Comment by genericuser-me** [comment]
Thanks, it worked fine. There was something wrong with the eventAggregator object. Moved the code to other file and event is getting fired.
