### ISSUE TITLE
Custom Element with Array Binding

### ISSUE THREAD

**Issue by JSeligsohn** [aurelia/framework#431]
I've seen some discussion related to observables and arrays, but nothing that seems to address my specific issue - I want to make sure this is a current bug in aurelia and not something I'm doing wrong. I have a view/view-model that contains a custom element. The view-model loads data from server and passes it into an array of "cards." The user can trigger more data to be loaded, which is added to the array.
_view.html_
```html
<template>
  <require from="./cards.js"></require>
  <div class="card-view">
    <cards cards.bind="cards"></cards>
  </div>
</template>
```
_viewmodel.js_
```javascript
export class CardDisplay {
  constructor() {
    ...
  }
  activate() {
   this.cards = [];
   return this.loadInitialData();
  }
  loadInitialData() {
     //call made to server that returns an array of data as response
     this.cards = response;
  }
  loadMoreData() {
    //user can trigger more data to be loaded from server
    response.forEach(function(item) {
      this.cards.push(item);
    });
  }
}
```
The array 'cards' is bound to the custom element - Cards - which does some manipulations to each element and then adds the element to an array - 'formattedCards' which is rendered in the DOM.
_cards.html_
```html
<div repeat.for="cards of formattedCards">
  <div class="card-container">
    <h1>card.Name</h1>
    <p>card.Description</p>
  </div>
</div>
```
_cards.js_
```javascript
import {inject, customElement, bindable} from 'aurelia-framework';
@customElement('cards')
export class Cards {
  @bindable cards;
  bind() {
    this.formattedCards = [];
  }
  cardsChanged() {
   var that = this;
    this.cards.forEach(function(item) {
      //manipulate cards - e.g. add a dynamic property or modify an existing one
      that.formattedCards.push(item);
    });
  }
}
```
The expected behavior is that whenever more data is loaded in the viewmodel.js, the `cardsChanged();` function should be triggered. Unfortunately it is not. It seems the observer only notices if the entire array changes (e.g. if the cards array is set to null) but not if more elements are added to the array. 

I'd like to know if anyone else has had this issue and if there's a workaround or if I'm just making a mistake somewhere.

**Comment by EisenbergEffect** [comment]
This is by design. The "array" instance never changes so you are never notified. If you would like to be notified for changes in the array's items, you need to set up a custom observer for that and respond to the change records that are produced from that. To set up the observer, you can use the BindingEngine's collectionObserver method. API is here: http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.3.5/doc/api/class/BindingEngine. Pass the array you want to observe and it will give you an observer for that array which you can call subscribe on: http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.3.5/doc/api/interface/CollectionObserver Subscribing returns an object with a dispose method that you can call later when you are done listening. Your callback will receive a list of change records which you can respond to.
