### ISSUE TITLE
GetStarted Minimized Menu Not Functioning

### ISSUE THREAD

**Issue by diahron** [aurelia/framework#457]
The minimized menu in the 'GetStarted' documentations do not function when screen is minimized. It display as minimized, but it don't display any menu items when you click on it.

**Comment by EisenbergEffect** [comment]
I'm not quite following. Can you provide some more specifics? Are you referring to the bootstrap menu from the skeleton?

**Comment by diahron** [comment]
Using the bootstrap menu from the skeleton. The demo works, but if you minimize your window you have the icon for a minimized menu, but it doesn't work. Click on it and nothing happens.

**Comment by EisenbergEffect** [comment]
Right. Is it not working in the skeleton? or is it only not working when following the "getting started" tutorial?

**Comment by diahron** [comment]
When following the getting started tutorial. Everything in the tutorial works except the minimized menu. It's as if the bootstrap.js or jquery.js is missing.

**Comment by EisenbergEffect** [comment]
Ok, yes. That is correct. You would need to add that. Th tutorial doesn't cover that but the skeletons include it automatically. I'm going to close this issue for now since we are creating new getting started materials launching within the month.

**Comment by diahron** [comment]
Is there a guide to follow to add that?

**Comment by EisenbergEffect** [comment]
Funny you should ask at this particular time.
There's actually a difficulty today because of version dependencies in bootstrap and a bug in jspm.
If you take a look at our starter kits, you'll see that we actually just add the script tags to the page for jQuery and then use the module loader for bootstrap.

Look here: https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext/index.html#L8
And here: https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext/src/main.js#L1
