### ISSUE TITLE
Difficult/Impossible to debug issues

### ISSUE THREAD

**Issue by ShaneCourtrille** [aurelia/framework#46]
Because most problems end up getting caught in app-router.js I'm finding it very difficult to debug the cause of mistakes I've made (in fact my current one is impossible to debug).  

Either I'm requesting that there be a small documentation section on debugging issues that are caught by the router OR a change so that we can see the actual source of issues.

**Comment by EisenbergEffect** [comment]
Can your provide a bit more information that would help us to get the specific type of debug support that you need?

**Comment by ShaneCourtrille** [comment]
Right now I have an error 'Cannot read property 'name' of undefined' and I have no clue why.  I'm importing a class from a js file and if I remove the import it works fine.  Currently the only way I can figure out how to debug this is to create an empty class and slowly add things until it breaks.  This is obviously not an optimal workflow.

**Comment by jdanyow** [comment]
@EisenbergEffect I think it's safe to close this one now.  It was fixed by https://github.com/aurelia/dependency-injection/pull/18

Found that the 'Cannot read property 'name' of undefined' error was coming from within the container code (util.isClass), typically when attempting to do things with an undefined key due to an import/dependency issue.  Now the container throws a better error.

**Comment by EisenbergEffect** [comment]
Great! I'm glad we added the meaningful error. We need to try to identify more things like this throughout the libraries so we can help developers along. Thanks for reminding me to close this issue!
