### ISSUE TITLE
Add TypeScript ViewModel Interface

### ISSUE THREAD

**Issue by TylerBrinkley** [aurelia/framework#481]
It would be nice if a TypeScript ViewModel interface was added for better visibility of available features. It might look something like the below. There's probably more methods that could be specified but I just haven't discovered them yet which would just show the utility of adding this.

    export interface ViewModel {
        activate?(): void;
        canActivate?(): boolean|Promise<boolean>;
        deactivate?(): void;
        canDeactivate?(): boolean|Promise<boolean>;
    }

**Comment by EisenbergEffect** [comment]
This is specifically related to the Router, so I'm moving it there. I'm not entirely sure the benefit since it wouldn't affect the runtime at all and it would force a deeper dependence in your code on our framework by making you implement the interface. I'd favor someone just creating it in their own project if they want.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/router #375](https://github.com/aurelia/router/issues/375) via [**ZenHub**](https://www.zenhub.com/)

**Comment by TylerBrinkley** [comment]
Thanks, sorry I added it to the wrong place.
