### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by kevinrenskers** [aurelia/framework#5]
Shouldn't aurelia be published to NPM? For something like node-webkit or atom-shell it would make a lot of sense to import the commonjs modules instead of using ES6 and a compiler.

**Comment by EisenbergEffect** [comment]
Yes, I think we can publish it all to npm. We are already generating commonjs code as one of our outputs. I think the packages are set up to point to that, but I need to double check. Mostly, I haven't deployed to npm because it's an extra target while I can do one single github deploy and have it available to jspm and bower. Is it possible to have  the  npm repo actually automatically stay in sync with a github release? That would be ideal. @kevinrenskers  Thoughts?

**Comment by kevinrenskers** [comment]
Not sure, I only have 3 NPM packages myself and simply run `npm publish` whenever I release a new version - [see docs](https://docs.npmjs.com/getting-started/publishing-npm-packages). How does it work for bower? I guess you only register your package url and they point to it? Unlike NPM where they host their own package registry and you have to push new versions.

**Comment by EisenbergEffect** [comment]
Yes. With bower you just register it once and then from there you can just release to github. It's not terrible inconvenient to npm publish. I'm just trying to keep our release checklist as streamlined as possible. I'll keep this issue open and see how we can best address this. Maybe we can automate it.

**Comment by kevinrenskers** [comment]
I've just learned that with NPM you can install `npm install someaccount/somerepo` - works for any github repo that has a package.json. So aurelia can already be installed without registering the packages to NPM.

**Comment by EisenbergEffect** [comment]
Oh yeah. I don't know why I didn't think about that. It's just ac
convenient actually because we would need to prefix the package names
anyways.

On Thu, Jan 29, 2015 at 12:04 PM, Kevin Renskers <notifications@github.com>
wrote:

> I've just learned that with NPM you can install npm install
> someaccount/somerepo - works for any github repo that has a package.json.
> So aurelia can already be installed without registering the packages to NPM.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/framework/issues/5#issuecomment-72062353>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by EisenbergEffect** [comment]
As it turns out you can npm install anything from github. So, you can always do `npm install aurelia-bootstrapper` The problem is that it won't handle all the client-side dependencies...because that's not something that npm does. We would need to hook up all the deps to make that work. I'm not sure if I want to do that just yet.

We will revisit this at a later point in time.

**Comment by kevinrenskers** [comment]
Yeah it's a little bit of a hassle that the dependancies are not installed with it. Now I had to do this:

npm install aurelia/framework --save
npm install aurelia/binding --save
npm install aurelia/dependency-injection --save
npm install aurelia/loader --save
npm install aurelia/logging --save
npm install aurelia/metadata --save
npm install aurelia/task-queue --save
npm install aurelia/templating --save

But these are just the top level dependancies of aurelia-framework. I now have to find out what the dependancies of each of this are, and so on and so on.

**Comment by chalisegrogan** [comment]
For whoever happens to come across this issue in the future, aurelia-framework is available here: https://www.npmjs.com/package/aurelia-framework
