### ISSUE TITLE
typings not included in jspm distribution

### ISSUE THREAD

**Issue by unional** [aurelia/framework#644]
Hi @EisenbergEffect ,

I finally get time to test jspm support for `typings`.
I notice when I install `aurelia` packages in jspm, the `package.json` and `*.d.ts` is not included.

Using `aurelia-pal` as an example, it points to `dist/amd` which does not have `*.d.ts`
Also, `package.json` should also be deployed to that we can find out where the typings file is located (same as what `tsc` does on `npm` side).

Can you take a look into it?

**Comment by jdanyow** [comment]
@unional take a look at the typescript skeleton. It uses typescript, typings and jspm:

https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript

**Comment by unional** [comment]
Please reopen. I'm a contributor of `typings`. This is directly related to adding `jspm` support in `typings`.

Currently, due to limitation of TypeScript support for `jspm`, we have to install the package both on `jspm` and `npm`, or install on `jspm` and use `typings install github:aurelia/***` to install the typings.

I'm adding `jspm` support in `typings`, so that user can do:

```sh
jspm i npm:aurelia-***
typings i jspm:aurelia-***
```

ping @EisenbergEffect

**Comment by EisenbergEffect** [comment]
Opening this to consider updating our distribution somehow.

**Comment by unional** [comment]
Thanks. The PR for this feature is at `typings/core` and there is one identified bug not related to this feature blocking the merge. I hope it will be merged soon.

**Comment by unional** [comment]
Hi, jspm support is landed in `typings` 2.0. So if `aurelia` distribute typings files during jspm install, it would be great. 🌷

**Comment by AdamWillden** [comment]
I've had a few issues relating to this. 

There's no other option, that I can see, than to distribute/duplicate the `.d.ts` in within each dist sub directory. 

[I've just remembered](https://github.com/aurelia/dialog/pull/280) that  following the move to typescript aurelia-dialog no longer exhibits the issue mentioned here because the `d.ts` is indeed [distributed/duplicated in each dist sub directory](https://github.com/aurelia/dialog/tree/master/dist/amd) ..and of course `aurelia-validation` built using typescript is the same.

Would it be an acceptable idea to update all non-TS libraries to distribute the d.ts in the same way? Are the d.ts files generated or manually updated? If manually updated I suggest the `d.ts` files are moved to source and then copied as part of the build task.

**Comment by AdamWillden** [comment]
Commonly used packages to check and update would be:

- [ ] dependency-injection
- [ ] event-aggregator
- [ ] fetch-client
- [ ] framework
- [ ] http-client
- [ ] logging
- [ ] logging-console
- [ ] metadata
- [ ] pal
- [ ] i18n
- [ ] task-queue
- [ ] templating
- [ ] templating-binding
- [ ] templating-router
- [ ] templating-resources
- [ ] testing
- [ ] router
- [ ] binding
- [ ] ui-virtualization

Any of these?

- [ ] animator-css
- [ ] animator-velocity
- [ ] bootstrapper
- [ ] history-browser
- [ ] history
- [ ] loader
- [ ] loader-default
- [ ] pal-browser
- [ ] path
- [ ] route-recognizer

Quite a list... and I fear I may have missed one or two.

**Comment by aluanhaddad** [comment]
I have written my own tool to handle this. It is far from ideal.

**Comment by atsu85** [comment]
@AdamWillden 
> Are the d.ts files generated or manually updated?

they are generated based on TS types in ES6 sources.

**Comment by davismj** [comment]
OP is asking for typings support for the jspm repository. [Typings is deprecated.](https://www.npmjs.com/package/typings).

The problem OP was trying to solve is "how do we make typescript and typescript-enabled IDEs aware of types installed by jspm." [The TypeScript team has noted](https://github.com/Microsoft/TypeScript/issues/6012#issuecomment-163348809) that analyzing jspm_packages for types the way it works with node_modules is not as viable because of the way that jspm versions packages.

jspm has [provided no further specification for specifying types](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm) that we can comply with. 

The less than ideal but not entirely painful solution is to run an npm install to get your types.
