### ISSUE TITLE
Support Typescript definitions via npm

### ISSUE THREAD

**Issue by HexWrench** [aurelia/framework#665]
Since Typescript 2.0, typings are easily acquired using npm. Unfortunately, Aurelia still uses `typings` so we have to use two different mechanisms.
Is it possible to publish the definition files so they are available in the [@types repository](https://www.npmjs.com/~types) and can be installed using e.g. `npm install @types\aurelia-framework --save-dev`.

**Comment by StrahilKazlachev** [comment]
Aurelia packs the definitions files in the npm packages as recommended by the TS [docs](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). In my projects I'm using neither `@types` nor `typings` tooling  for aurelia packages.

**Comment by HexWrench** [comment]
I use jspm for Aurelia and here the definitions aren't included.

**Comment by jdanyow** [comment]
right- aurelia uses the recommended `types` field in the package.json: https://github.com/aurelia/binding/blob/1.0.9/package.json#L17

**Comment by HexWrench** [comment]
So I have to install Aurelia using jspm and npm?

**Comment by jdanyow** [comment]
When you execute `npm install aurelia-binding`, the definition files are included.

The TypeScript compiler can locate them without using typings or using `npm install @types/aurelia-binding` because the package.json tells the compiler where they are via it's [`types`](https://github.com/aurelia/binding/blob/1.0.9/package.json#L17) attribute.

This is TypeScript's recommended way of distributing definitions because it eliminates the need for additional installs provided you are using npm.

Here's is the documentation:

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md#including-declarations-in-your-npm-package

**Comment by atsu85** [comment]
@jdanyow, @HexWrench is using jspm, not npm to install clien-side dependencies, like aurelia-binding. If I remember correctly, JSPM has still issues with distributing TypeScript type declarations

**Comment by HexWrench** [comment]
I installed Aurelia using npm as dev-dependency now too, so this works. But it would be cleaner if we could just install the definitions.

**Comment by atsu85** [comment]
@HexWrench, this workaround for JSPM (installing client-side dependency as dev-dependency in addition to regular dependency) isn't much (if any) better compared to manually installing typings of the dependency in addition to the regular dependency).

**Comment by HexWrench** [comment]
@atsu85 I know, but it works fine with Typescript 2.0 which automatically finds definitions inside the node_modules folder.
