### ISSUE TITLE
Arelia CLI (au new) does not use latest packages in new projects

### ISSUE THREAD

**Issue by boshinski** [aurelia/framework#701]
**I'm submitting a bug report**

* **Library Version:**
AURELIA-CLI 0.24.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
4.5.0

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
NA

* **Browser:**
NA

* **Language:**
TypeScript 2.0

**Current behavior:**
Creating a new project with aurelia-cli ("au new") does not use the latest packages. For example, created a new TypeScript project and then ran "ncu" and it displayed the following:
```
aurelia-bootstrapper             ^1.0.0  →  ^2.0.1
aurelia-tools                    ^0.2.2  →  ^1.0.0
gulp-typescript                 ^2.13.6  →  ^3.1.4
gulp-tslint                      ^5.0.0  →  ^7.0.1
tslint                          ^3.11.0  →  ^4.3.1
typings                          ^1.3.0  →  ^2.1.0
karma                          ^0.13.22  →  ^1.4.0
karma-chrome-launcher            ^1.0.1  →  ^2.0.0
karma-typescript-preprocessor    ^0.2.1  →  ^0.3.1
```
I believe the issue also occurs in new ESNext projects as well.

**Expected/desired behavior:**

* **What is the expected behavior?**
I would expect it to use the latest released versions of the packages.

* **What is the motivation / use case for changing the behavior?**
Avoid the need for the developer to manually upgrade each of these packages when creating a new Aurelia project with the CLI.

**Comment by AshleyGrant** [comment]
For the non-aurelia packages listed, this is expected behavior. We would not want to automatically update the package to a new major version without first testing it. That being said, we can likely update all of these dependencies after we have done some testing to make sure everything still works.

A PR for this would be greatly appreciated, but I will try to work on this on my flight today. Thanks @boshinski!

@EisenbergEffect please move this issue to the CLI repo and assign me, if possible. I'll create a PR later today.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/cli #468](https://github.com/aurelia/cli/issues/468) via [**ZenHub**](https://www.zenhub.com/)
