### ISSUE TITLE
community.aurelia.io

### ISSUE THREAD

**Issue by brylie** [aurelia/framework#704]
Aurelia lacks a dedicated community platform for asynchronous discussion. Gitter is great for real-time chat and StackOverflow is great for Q&A, but neither is great as a general community discussion platform.

Please consider setting up an instance of the open-source [Discourse community platform](https://www.discourse.org/). Discourse even provides [free hosting for open source communities](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/).

Providing a dedicated community discussion platform can help aurelia grow in strength and popularity.

**Comment by swalters** [comment]
This has been brought up many times before and keeps getting shot down.  I've never had to manage a large community so I don't know all the work involved to keep the spammers and trolls out.  I'm sure it's not trivial.  However, this type of community IS needed.  SO is for question/answer only.  There's no where I can converse with the community about best practices, etc.

**Comment by brylie** [comment]
> I've never had to manage a large community so I don't know all the work involved to keep the spammers and trolls out. I'm sure it's not trivial. 

One thing worth noting, if we see Discourse as a good option for the community platform, we can benefit from built-in defaults that deter SPAM and abuse (as well as being able to flag 'uncivil' behavior).

**Comment by RomkeVdMeulen** [comment]
What about the [Aurelia subreddit](https://www.reddit.com/r/aureliajs/)?

**Comment by brylie** [comment]
> What about the Aurelia subreddit?

It is pretty good, yes. Perhaps could use more activity.

Honestly, though, Reddit pales in comparison with a dedicated forum, such as Discourse.

**Comment by brylie** [comment]
Here are a few examples, from semi-related projects:

- [React discuss](https://discuss.reactjs.org/)
- [Vue Forum](https://forum.vuejs.org/)
- [Meteor forums](https://forums.meteor.com/)

**Comment by brylie** [comment]
> This has been brought up many times before and keeps getting shot down.

What are some of the main concerns **against** having a dedicated community forum? Perhaps we can work through some of them with a bit of organizing.

**Comment by EisenbergEffect** [comment]
Is there some reason that Stack Overflow isn't acceptable? My primary reason for avoiding forums is maintenance.  It's another channel the entire team has to attend to every day, which means less work on issue triage, bug fixes and new features. So far, we have: Stack Overflow for questions. GitHub for bug reports and feature requests (and discussions related to these items). Gitter for quick feedback and help. Blog for news and announcements. Hub for documentation. What whole will the forum fill?

**Comment by BrainBuzzer** [comment]
I don't feel like there is a need of forums for Aurelia yet. Stack Overflow community is amazing and always ready for instant reply. For most of other frameworks forums, they go blank at some point and solution is not provided. For now, sticking with Stack Overflow is good.

**Comment by jpsala** [comment]
Please reconsider, I really think it would be great for the growth of the
community to have a nice forum, I definitely would love it, it's nearly
imposible to learn from gitter, and stack overflow its better but not so
much, maybe you can make a pull? sorry about my English

**Comment by swalters** [comment]
Stack Overflow is strictly for question/answer. It's not made for discussions. That's why Atwood created Discourse.  Great explanation in this podcast. http://2ketodudes.com/show.aspx?episode=47.   A topic like 'What are the current best UI components for Aurelia' is too vague of topic for SO.

Gitter is great for quick replies, but it's junk for long conversations. Searching in gitter is painful.

**Comment by AshleyGrant** [comment]
I feel personally that the aurelia subreddit could quite easily handle this need. It offers a simple way to ask opinion based questions and people can upvote and downvote answers as well as reply to answers in a threaded fashion.

**Comment by CasiOo** [comment]
I'm personally looking forward to the `Aurelia cookbook` that has been discussed before. A section in the hub with recipes, setup examples, submit their different ways of accomplishing a task, and hopefully an easy way for people to submit and improve it. A cookbook that should be maintained by the community without the need for the Aurelia team to interfere too much.
I think there's an open issue somewhere about this cookbook suggestion.
^ But that isn't exactly a community platform either I would say ^^

**Comment by swalters** [comment]
@AshleyGrant Reddit is the platform you want to be presented to business leaders?  I'll pass.

![reddit the front page of the internet 2017-02-13 17-00-26](https://cloud.githubusercontent.com/assets/195646/22907319/16f44cc4-f20e-11e6-8af2-47ef7fca28a4.png)

**Comment by AshleyGrant** [comment]
I'm not sure why content on other subreddits matters. The Aurelia subreddit doesn't have that content you screenshotted.

There are plenty of great communities on reddit. The Angular subreddit is fairly active. As the community lead, I think that fostering a great community on one of the leading community sites in the world is a good idea.

**Comment by brylie** [comment]
> There are plenty of great communities on reddit.

Here are a few examples of other active frontend/full stack communities on Reddit:

- [Meteor](https://www.reddit.com/r/Meteor/) > 4,000 readers
- [React.js](https://www.reddit.com/r/reactjs/) > 19,000 readers
- [Vue.js](https://www.reddit.com/r/vuejs/) > 3,000 readers

Comparing (https://www.reddit.com/r/aureliajs/) to the above:

- around 600 readers
- generic design/branding
- two moderators, unclear of relationship to Aurelia project
  - [NewNole2001](https://www.reddit.com/user/NewNole2001)
  - [Davismj](https://www.reddit.com/user/Davismj)
- currently (2017-02-14 0730 UTC) top 24 posts consist of
  - 9 discussion topics (self.aureliajs)
  - 15 'promotional' topics (links to blogs, books, videos, etc)
    - 6 links to the official aurelia blog

**Comment by mttmccb** [comment]
Personally happy with the community setup, apart from Gitter, it's good for linking to github and tracking things but doesn't really foster a community, why not slack or discourse?

Reddit is a little nasty in my experience.

**Comment by AshleyGrant** [comment]
@brylie 
NewNole2001 is me. Davismj is @davismj another core team member.

I'm really not sure what the point you are trying to make is though. Currently, the subreddit isn't not promoted as a way for our community to interact with each other. We promote the Gitter Channel, GitHub issues, and Stack Overflow questions for this. Each of these avenues is currently very active.

If we were to promote the Aurelia subreddit as a place for the community to have discussions that:
- don't work well as chats 
- are bad Stack Overflow questions (an example of a bad Stack Overflow question is "What's the best grid to use with Aurelia?" as opinion based questions aren't allowed there)
- are not bugs w/the framework

then the community would come. Reddit is a ready-made platform to enable this type of community. It offers threaded conversations, a form of community moderation (up/down voting), and a ton of people already have accounts there.

The other thing, to touch on @mttmccb's point, is that I completely agree that reddit can be a nasty place. But there are also some amazing communities on reddit. And when you create an account on reddit, you aren't forced to subscribe to any subreddits you don't like. So people could create an account that is only subscribed to the Aurelia subreddit and avoid all of the bad parts of reddit.

**Comment by brylie** [comment]
> I'm really not sure what the point you are trying to make is though.

The point was to make note of the current 'state of aureliajs reddit'.

> If we were to promote the Aurelia subreddit as a place for the community to have discussions then the community would come.

Perhaps the main point of this issue is that the Aurelia community need and deserve an 'official' discussion platform.

> I completely agree that reddit can be a nasty place.

I harbor additional concerns about Reddit in terms of usability, design, and focus that could be better addressed by a 'ready-made platform' such as [Discourse](https://en.wikipedia.org/wiki/Discourse_(software)), which offers [free hosting for open source projects](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/).

In effect, the recommendation for and **adoption of Discourse as a community platform for open source projects is not arbitrary**. Discourse has excellent usability, and has put itself on a tier above pretty much every other open source discussion platform (e.g. phpbb, vanilla forums) and even free and/or proprietary mailing lists (e.g. Google Groups, or Mailman).

**Comment by brylie** [comment]
Note: bold text above is for clarity and emphasis.

**Comment by adriatic** [comment]
A Community Forum (platform for discussion of issues of importance to Community members) does not need to be run and moderated by the Aurelia core team. Having a well defined group of volunteers from the Aurelia Community to create and manage such site would be a lot better choice and it would address **[Rob's concern](https://github.com/aurelia/framework/issues/704#issuecomment-279453078)**. 

As someone who was able to devote full time (and more) to Aurelia for the last two years, I will try to create this project ASAP, as I personally am very interested in it. Anyone caring to join, please let me know and I will invite you to  a gitter room to plan next steps

**Comment by brylie** [comment]
> As someone who was able to devote full time (and more) to Aurelia for the last two years, I will try to create this project ASAP, as I personally am very interested in it.

One goal of this discussion is to have 'official' support for the community forum. E.g. the aurelia.io website would have a link to the community forum. So, it is important that we do this in tandem with the Aurelia core team.

**Comment by adriatic** [comment]
@brylie
> One goal of this discussion is to have 'official' support for the community forum. E.g. the aurelia.io website would have a link to the community forum. **So, it is important that we work in tandem with the Aurelia core team**.

Your arguments are very clear and reasonable - however, they exclude my offer, as only Rob can create what you are asking for, and only then will it be possible to claim the size of the audience that Discourse requires for free hosting.

In the mean time, while waiting on Rob's decision, you may watch a much smaller forum created for Aurelia-UI-Toolits and Aurelia Tools community at http://forum.aureliatools.com/ (which has yet to be initialized)

**Comment by lazaridis-com** [comment]
Possibly some remarks from an outsider help:

@adriatic , know that I don't even look at such kind of forums (http://forum.aureliatools.com/)

@EisenbergEffect , StackOverflow is annoying and distracting and has a terrible ui. It's usually my last choice where I ask. 

@AshleyGrant , reddit is reddit  - another non-standard communication resource, but with an own dynamic (e.g. a forum for a product can pop-up by itself).

@brylie , Discourse is a product, and not a good one (i guess the usual happens here: companies and projects pick it, just because its easy, and because others do it, and because not much else is available).

For analytic discussions, I personally prefer standard email, which allows inline-commenting. So, google-groups (or similar) would be for me the 1st choice.

If a project is hosted on github, then I prefere to keep any issues i have on the... issue-tracker, as it allows to interlink other issues, code etc.

Would I need to discuss something more, the I would prefer at this moment reddit.

And of course: the best thing would be a good-old usenet-group. But I don't even know if usenet exists anymore...

**Comment by JordanMarr** [comment]
In the past I have championed Durandal over Angular 1 on my team as I am a big fan of the convention over configuration design decisions.  As a result, we have delivered some very nice projects using that framework.  

Now my team lead has pressured me to use Angular 2 on our last big web project due to its inevitably higher adoption rate.  With a another big client web project about to start this month, I began to make a case for Aurelia based again on the convention over configuration argument.  I was countered with the protest that it does not have as big of a community.  I said that Durandal always had a loyal following, and he said, "show me the forum."  
To my surprise, the official Aurelia site had no forum link, and the there was no google.groups forum like Durandal had.  So we googled and found the Reddit.  

Now I personally don't have a problem with those, as I am sure any technical issues I might have would be quickly answered there; however, my team lead definitely was dubious to say the least.  Not having an official community site did not counter the logical "there is no community around Aurelia" argument.  

And really, that is probably the single biggest - nay, the only - argument against Aurelia at this point.  So what I'm saying is, it seems important. 

"Perception is everything."

Still not sure what to do on this next project.  
That's my 2c.  Carry on.

**Comment by Thanood** [comment]
Well, you *can* create a nice subreddit. For example Angular2 has a nice one.

**Comment by adriatic** [comment]
@EisenbergEffect Rob, this issue does not seem to be going away. I offered a [solution](https://github.com/aurelia/framework/issues/704#issuecomment-283178612) that is perceived as [not official enough](https://github.com/aurelia/framework/issues/704#issuecomment-283288879). So, I would hate to go against such (well meant and good) advice and I also hate to see Durandal customers go to Angular 😏

**Comment by davismj** [comment]
@Thanood Noted. I'm gunna take a look at it and try to spruce it up.

**Comment by AshleyGrant** [comment]
@JordanMarr if your team lead is pressuring you to move to Angular 2 due to it having a larger adoption rate, then he or she is in for a bad time. The JavaScript developer community is a fickle bunch. Pick the tool that supports your team's goals the best, not what everyone is using today, b/c the masses seem to move on quite quickly these days, as evidenced by large numbers of NG1 devs moving to Vue instead of NG2|4.

**Comment by EisenbergEffect** [comment]
We're in the process of investigating putting together forum for Aurelia as part of our new Aurelia Hub release.

**Comment by adriatic** [comment]
My offer withdrawn. Thank's Mr. Eisenberg 👍

**Comment by brylie** [comment]
Woohoo! 😃

**Comment by irashid25** [comment]
Been looking forward to this for a long time. 

Hope it works out.

**Comment by swalters** [comment]
@EisenbergEffect any updates?

**Comment by EisenbergEffect** [comment]
Very soon. Almost ready.

**Comment by Alexander-Taran** [comment]
https://discourse.aurelia.io/ is there.

can be closed
