### ISSUE TITLE
Question: Is (or will) Aurelia really (be) better than Angular from a business perspective?

### ISSUE THREAD

**Issue by smolinari** [aurelia/framework#74]
Hi,

This is more a question than an issue. Sorry if this is the wrong place to ask, but it is just too elaborate a question for a chat room (you really need a forum :)).

We are still in the process of making a choice for our system's client-side application architecture and I am currently [reading a pretty good book about Angular](https://leanpub.com/web-component-development-with-angularjs/read). I noticed the comparison between Angular and Aurelia in the Aurelia docs and found the differences quite interesting and attractive. Aurelia just seems more logically built and more semantic (though I must admit, I am personally far from a JS expert). 

My concern is more the business side though. What would be the motivational factors from a business standpoint to chose Aurelia over Angular? What are the conceptual differences, which would make anyone (especially us) want to use Aurelia more over Angular? Our project has a long way to go, but we love Aurelia's forward looking direction. What else is there, we should know about? We want to be able to build on the web components standard i.e. shadow DOM (hopefully of the future?). This is a must, as our system will be strongly widget based and we want widgets to be interchangeable among our customers too. With that in mind, we'd love to know how Aurelia will support that direction. 

Thank you in advance for any input.

Scott

**Comment by kristianmandrup** [comment]
I can tell from my own experience, that both Angular and Ember were horrible developer experiences as soon as you started stepping outside the "golden path" of what was built in. Looks like it will be pretty much the same experience with Angular 2. If you choose Angular 1.x currently, it will likely be quite some rework to upgrade it to 2.x down the road. Aurelia on the other hand is built as a set of micro modules, which makes it very flexible. Contrary to typically frameworks which are convention based, Aurelias prides itself on making almost no assumptions and just a minimal set of conventions for ease of use which are very easy to reconfigure or override. Aurelia is for the developer who wants more control and freedom when stepping outside the box. Ember and Angular are for developers who want to constrain themselves to a set of very specific conventions etc. and then leverage productivity by using their larger set of components, community, integrations etc. So it all depends on what type of project/developer you are and what you are looking for in a framework. Personally I like to be less constrained and have more freedom... Cheers!

**Comment by smolinari** [comment]
Thanks Kristian. 

I thought the missing constraints/ lack of opinionation in Aurelia was simply because it is so new. LOL! :-D

But, if that is actually a core concept and will be carried forward in the future, fantastic! I've been actually thinking to just go with Backbone, because of the lack of opinionation the whole time, but then Angular was attractive, because it also thought along the lines we need to head on. But Aurelia offers a lot more towards that end too and also seems modelled a lot better to the common practices I am already used to as a back-end dev. As I mentioned above, Aurelia just seems semantically more correct. Maybe the right word is more "familiar"?

And things like [the way templating works](http://aurelia.io/docs.html#templating), well oh boy, that is just making me drool, because it fits exactly to our needs, to let the users of our system share web components/ widgets. Cool stuff! :-)

Scott

**Comment by EisenbergEffect** [comment]
From a business perspective, Aurelia is backed by Durandal, Inc. Durandal is a company that is dedicated to providing open, free and commercial tools/services for developers and businesses that create software using web technologies. We see Aurelia as our foundational product and developers as our customer. This is a very important point to make because Google does not see Angular or Polymer as an official product at all and they don't see developers as customers. We will provide commercial support, for example, but they cannot. That is not something aligned with their business.

Aurelia itself is solid due to the fact that it currently has a 12 person development team distributed throughout the world and a large active community, especially considering it was only announced a couple of months ago. No one company is dictating the full design and all members of the team are building apps with their day jobs. This means the framework is positioned much better to meet the needs of the real world. No one on the team is exclusively a "framework builder" who does not build real apps. With respect to Angular, this is a major problem they have.

You will see a solid set of training materials on Aurelia. A Pluralsight course is already being prepared. We have an invitation from a publisher to write a book and we're preparing our own documentation, training materials and video tutorial series. Aurelia workshops are also being offered at multiple conferences this year, around the world. It's likely all this will be available long before Angular 2.0 is released.

Durandal is positioned to begin raising Series A venture capital this month. That isn't to support the open source Aurelia project. That project does not need funding. Rather, it is to support Durandal Inc. which intends to offer a much richer set of tooling and services for those who want to leverage Aurelia and the web. We are building out a serious business and our entire platform will be built with Aurelia and for Aurelia. Our potential investors are very excited about our plans and we expect to have some cool stuff to show in the future. These are things which Google, for example, just cannot accomplish due to the nature of their business. They are things that are in the best interest of developers though...and it's developers who are our customers and who we care about and want to see succeed most.

**Comment by smolinari** [comment]
Where is a like button, when you need one.:-) Thanks Rob. I appreciate the openness and the support. Looking forward to all the learning materials and to Aurelia 1.0. Is there a rough road map for 1.0? Like, will it be ready this year?

Scott

**Comment by EisenbergEffect** [comment]
Yes, it will definitely be ready this year :) We hope you'll see some of the other offerings start to appear this year as well.

**Comment by smolinari** [comment]
Like, like, what?:D 

Scott

**Comment by kristianmandrup** [comment]
I will make a guess that 1.0 will be ready sometime this summer, i.e. sometime between June and August.

**Comment by smolinari** [comment]
What "other offerings" will there be? Aurelia 1.0 is already a great one.:-D

Scott

**Comment by jimschubert** [comment]
@EisenbergEffect thanks for your excellent answer. I feel like a question like this would have been closed without explanation on many other open source projects (Angular included). Your willingness to communicate with developers alone makes me want to start using Aurelia, but the company backing and developer focus is a strong argument for Aurelia over Angular.

**Comment by opensas** [comment]
This answer should find it's place on aurelia's home page, a FAQS section with the "Why should I choose Aurelia?" label

**Comment by The1nternet** [comment]
+1 answer on home page

**Comment by kjeske** [comment]
@EisenbergEffect, I love your work! The only problem (?) I see is that you are the only active contributor for now, the rest have minimal impact on the Aurelia's code. Is it going to change? Angular, in contrast, has at least 10 active developers and that makes it more safe from business perspective. But nothing will change the fact, that your concepts in Aurelia are just great.

**Comment by EisenbergEffect** [comment]
We have 17 members on our core team currently which contribute daily. If you are only looking at this repo, then that might throw you off. `aurelia-framework` mostly aggregates the other repos and then provides a small framework-level api. The bulk of aurelia is distributed across a couple dozen different libraries. We even have different teams within our team that are focused on different libraries within the framework. It's definitely not just me. Far from it. In fact, most of the day-to-day work on Aurelia itself is now being done by other team members.

**Comment by kjeske** [comment]
@EisenbergEffect, So it sounds really great! Thanks for clarifying this.

**Comment by ghithub** [comment]
I feel like startups like to mess with those _fancy fresh-looking_ JavaScript front end frameworks/libraries. There are so many in the market, most of them don't last long. So, my suggestion is: Stay with mature, mainstream technologies, use native JavaScript or jQuery. Observe a new framework/library for a couple of years before you decide to use it in your project.

**Comment by samuelmukoti** [comment]
Enjoyed watching the Polymer summit last week.   Really like where they are going with it in version 2.0  Looks like Aurelia and Polymer will work well together.  Any thoughts?

**Comment by smolinari** [comment]
Isn't Aurelia and Polymer covering the same domain, i.e. front-end application development? In other words, they are competitive frameworks?

Scott
