### ISSUE TITLE
Modularizing Stylesheets

### ISSUE THREAD

**Issue by omidkrad** [aurelia/framework#87]
First of all I want to say that I'm really happy to see this framework. I'm looking forward to build my next projects using Aurelia.

My question: Does Aurelia have any modularization for stylesheets? For example put `<module-name>.css` file next to `.js` and `.html` files? Also is there any out-of-box support for any compiled css solution, such as SASS or LESS? Thanks!

**Comment by jdanyow** [comment]
@omidkrad I think this is being tracked **[here](https://github.com/aurelia/framework/issues/50)**.

**Comment by omidkrad** [comment]
You're right. I'm closing this issue then.

**Comment by delebash** [comment]
I am just now testing support for SASS in the build scripts,  I will push a forked repo of the skeleton nav when done, but here is working code, you can delete the path materialize or replace it with a path to another sass lib like bootstrap-sass-official.  This is not aurelia specific just a plain old sass task to gulp, as far as adding a css or scss file along with html and js of the same name, I think that still needs to be worked out, this just gets you up and running using sass. 

Add to build\tasks\build.js
Add as another require statement
```var sass = require('gulp-sass');```

 Add as another build task
```
gulp.task('build-sass', function () {
    gulp.src(paths.sass + '**/*.scss', {base: paths.sass})
        .pipe(sourcemaps.init())
        .pipe(sass({
            style: 'expanded',
            includePaths: [
                paths.sass,
                paths.jspmDir + '/github/Dogfalo/materialize@0.96.0/sass',
            ],
            errLogToConsole: true
        }))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(paths.cssOutput))
});
```

Add to build\tasks\watch,js
Add as another watch task
``` gulp.watch(paths.sass, ['build-css',browserSync.reload]).on('change', reportChange);```

Add to build\paths.js
  ```sass: appRoot + 'sass',```
Replace styles: with   ```css: appRoot + 'css/**/*.css', ``` 
I renamed and adjusted the styles: because I like it named css better and also instead  of the folder being in the root I moved under src, just my preference

Add   ```sass: appRoot + 'sass','```
Add   ```cssOutput: outputRoot + 'css',```

Add gulp-sass to package.json by running npm install gulp-sass --save-dev

That's it you should be able to create a styles.scss file in a folder called css under the src folder, then run gulp build or gulp watch
