### ISSUE TITLE
VM interface typings

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/framework#874]
**I'm submitting discussion request**

* **Language:**
TypeScript

**Current behavior:**
There is no way to get intellisense for lifecycle hooks like activate / deactivate
Recent discussion about canceling dialog close and passing viewmodel https://github.com/aurelia/dialog/issues/344
got me thinking.
**Expected/desired behavior:**
What if we could have an interface with signatures for those hooks.
And allow to "implement" that interface in VM

* **What is the motivation / use case for changing the behavior?**

so one can have better discovery experience

----
apparently it can not be done at the moment.
having defined an interface like this
```
export interface AureliaVM {
	activate?:(params?:any, routeConfig?:RouterConfiguration, navigationInstruction?:NavigationInstruction) => void | Promise<any> 
}
```

Although partial info is visible
![image](https://user-images.githubusercontent.com/1029452/37592787-d8b1b188-2b80-11e8-9506-f595453e8be4.png)

You can't yet get fully typed signature completion out of it
https://github.com/Microsoft/vscode/issues/20134
https://github.com/Microsoft/TypeScript/issues/7158

**Comment by StrahilKazlachev** [comment]
@Alexander-Taran I'm against. This has been brought to attention at one time or another. There is an issue, can't find it currently, with a discussion. It is in the *router* - where we introduced the [`RoutableComponent...`](https://github.com/aurelia/router/blob/1.5.0/src/interfaces.js#L109) interfaces.
The `activate`/`deactivate` life cycle:
1. is **not** available everywhere
2. **where** available the signatures of the methods differ

Since you are bringing this in light of an issue in `aurelia-dialog`, [here](https://github.com/aurelia/dialog/blob/1.0.0-rc.2.0.0/src/interfaces.ts#L6) are the interfaces with the proper signatures for that case.

@EisenbergEffect in the [API doc](http://aurelia.io/docs/api) *dialog* and *validation* are missing, they were available in the old version. Ping me if there is something that needs fixing in the docs generation.

**Comment by Alexander-Taran** [comment]
@StrahilKazlachev thanks for pointing the interfaces out.
are there as well interfaces for component lifecycle ?
I'll search myself.. but if you remember where - it'd be great

**Comment by StrahilKazlachev** [comment]
@Alexander-Taran if you mean `bind`, 'attached', ..., the yes. They are in `aurelia-templating`.

**Comment by Alexander-Taran** [comment]
@StrahilKazlachev cool.
thanks
