### ISSUE TITLE
Event Handlers for DOM Event Listeners Lose the Context of "this"

### ISSUE THREAD

**Issue by SebGX** [aurelia/framework#881]
**I'm submitting a bug report**

* **Library Version:**
3.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10 Pro, version 1709, build 16299.371

* **Node Version:**
8.10.0

* **NPM Version:**
5.8.0

* **Aurelia CLI OR JSPM OR Webpack AND Version**
CLI 0.32.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
If you add a DOM event listener, the "this" keyword loses its context in the event handler when the event is raised:
```typescript
export class SomeClass {
  someProperty: number = 0;

  activateEvent(someElement: Element) {
    someElement.addEventListener('click', this.clickEventHandler);
  }

  clickEventHandler(event: Event) {
    // The "this" keyword in the context of this method does not reference an instance of the
    // containing class when the event is raised.
    this.someProperty += 2;
  }
}
```

**Expected/desired behavior:**
Given that the event handler is an instance method, the reference to its object instance should be preserved.

If the issue cannot be resolved because of an underlying component that is not managed by the team, please may you look at the Tweaky workaround below and consider adopting it as the convention in the docs? Would be great to have a "supported" approach.

* **What is the motivation / use case for changing the behavior?**
Preserving object instance references results in more stable code and less messy / hacky workarounds.

**Workarounds**
* **Messy - Define the event handler in the constructor**
```typescript
export class SomeClass {
  someProperty: number = 0;
  clickEventHandler = null;

  constructor() {
    this.clickEventHandler = (event: Event) => {
      this.someProperty += 2;
    }
  }

  activateEvent(someElement: Element) {
    someElement.addEventListener('click', this.clickEventHandler);
  }
}
```

* **Hacky - Get an instance from the DI container**
```typescript
export class SomeClass {
  someProperty: number = 0;

  activateEvent(someElement: Element) {
    someElement.addEventListener('click', this.clickEventHandler);
  }

  clickEventHandler(event: Event) {
    let self: SomeClass = Container.instance.get(SomeClass);
    self.someProperty += 2;
  }
}
```

* **Tweaky - Use the language to help**
```typescript
export class SomeClass {
  someProperty: number = 0;

  activateEvent(someElement: Element) {
    someElement.addEventListener('click', this.clickEventHandler);
  }

  clickEventHandler = (event: Event) => {
    this.someProperty += 2;
  }
}
```

**Comment by bigopon** [comment]
All `Element` subclasses (used to implement) extend base (used to be interface) class `EventTarget`. When an event is dispatched, the callbacks or listeners will be invoked with the context is the object that called `addEventListener`. In your example, it will be `someElement`, which is the expected behavior. There are many ways to handle this, some like you described above, some others are:

### With plain JavaScript

- Use `handleEvent`

```ts
export class SomeClass {
  someProperty: number = 0;

  activateEvent(someElement: Element) {
    someElement.addEventListener('click', this);
    // remove:
    // someElement.removeEventListener('click', this);
  }

  handleEvent(e: Event) {
    if (e.type === 'click') {
      this.clickEventHandler(e);
    }
  }

  clickEventHandler(event: Event) {
    // let self: SomeClass = Container.instance.get(SomeClass);
    // self.someProperty += 2;
  }
}
```

- Use `Function.prototype.bind`

```ts
export class SomeClass {
  someProperty: number = 0;

  constructor() {
    this.clickEventHandler = this.clickEventHandler.bind(this);
  }

  activateEvent(someElement: Element) {
    someElement.addEventListener('click', this.clickEventHandler);
    // remove:
    // someElement.removeEventListener('click', this.clickEventHandler);
  }

  clickEventHandler(event: Event) {
    // ...
  }
}
```

For more information how it works (it's quite simple), you can have a look at https://developer.mozilla.org/en-US/docs/Web/API/EventTarget how it would be implemented in JavaScript.

Recommendation: use `handleEvent` where possible, it's cleaner, more memory friendly. 

---

### With Aurelia helper:

There is a class in Aurelia to help you manage events in simple way: `ElementEvents`, like following example:

```ts
import { ElementEvents, Disposable } from 'aurelia-framework';

export class SomeClass {
  someProperty: number = 0;
  events: ElementEvents;
  clickSubscription: Disposable;

  constructor(element: Element) {
    this.events = new ElementEvents(element);
    // subscribing:
    this.clickSubscription = this.events.subscribe('click', (e: Event) => {
      // ...
    }, false /* it's an unexpected implementation, kept as is for avoiding breaking changes, wouldn't hurt if omitted but recommended to specify */);
  }

  // Then later, disposing subscription:
  this.clickSubscription.dispose();
  

  // or if you subscribed alot, and don't wanna keep track of any, then dispose all
  this.events.disposeAll();
}
```

---

Note: Your solution with `Container` getting the instance only works when `SomeClass` will only ever be created once, which won't be true in many cases.

**Comment by SebGX** [comment]
@bigopon Thank you very much for the detailed response. I'm kicking myself right now, handleEvent is absolutely the right way to do this... thank you.

**Comment by AshleyGrant** [comment]
TIL about `ElementEvents`.. There's a slightly uglier way to handle this without using `ElementEvents`, though I'd use `ElementEvents` now that I know about it. I'm putting this here b/c it's good to learn about the pattern of using arrow functions to keep `this` being what you expect it to be. You can run the example here: https://gist.run/?id=5ad8fa46f8e6e0bbf0936ce9e020a46a

```javascript
export class SomeElement {
  myText = 'Hello';
  wrappedHandler = event => this.handler(event);
  attached() {
    this.myButton.addEventListener('click', this.wrappedHandler);
  }
  
  detached() {
    console.log('detached')
    this.myButton.removeEventListener('click',this.wrappedHandler)
  }
  
  handler(event) {
    alert(this.myText);
  }
}
```

I create a property that wraps the call to the function with an arrow function. This makes `this` be what you expect it to be.

But can we do better? Wrapping every event handler like this would get rather old. Well, there sure is. Instead of creating a "normal" function on our class, we can have the function be declared as an arrow function, like this:

```javascript
export class SomeElement {
  myText = 'Hello';
  attached() {
    this.myButton.addEventListener('click', this.handler);
  }
  
  detached() {
    console.log('detached')
    this.myButton.removeEventListener('click',this.handler)
  }
  
  handler = event => {
    alert(this.myText);
  }
}
```

A runnable example is here: https://gist.run/?id=afe88e044f77fdec7815a4520ae6c712

That being said, I'd be inclined to still use `ElementEvents` as it makes cleaning up event subscriptions waaay simpler. Thanks for the tip @bigopon!

**Comment by AshleyGrant** [comment]
Also, I want to mention that you should use the templating/binding engine to attach/remove event handlers if at all possible. The stuff mentioned above is a fallback when, for some reason, that isn't possible.

**Comment by Alexander-Taran** [comment]
this is gold
someone please make a guide of this thread.. 
https://github.com/aurelia-contrib/aurelia-getting-started/tree/master/guides

**Comment by doktordirk** [comment]
for fun i'll add:

Use the binding operator ::
`::this.clickEventHandler` or `this::this.clickEventHandler`  for `this.clickEventHandler.bind(this)`

```js
export class SomeClass {
  activateEvent(someElement: Element) {
    someElement.addEventListener('click', ::this.clickEventHandler);
    // remove:
    // someElement.removeEventListener('click', ::this.clickEventHandler);
  }

  clickEventHandler(event: Event) {
    // ...
  }
}

**Comment by bigopon** [comment]
`::this.clickEventHandler !== ::this.clickEventHandler` or `this.clickEventHandler.bind(this) !== this.clickEventHandler.bind(this)` so the bound function reference will need to be stored somewhere.
